# WARNING - Generated by {fusen} from dev/flat_dev_1_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fetch_fts_data works", {
  expect_true(inherits(fetch_fts_data, "function")) 
})
