# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_funding_status_timeline works", {
  expect_true(inherits(plot_funding_status_timeline, "function")) 
})
