# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_recipient_contribution_type works", {
  expect_true(inherits(plot_recipient_contribution_type, "function")) 
})
