# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("indicator_destination_funding_diversity works", {
  expect_true(inherits(indicator_destination_funding_diversity, "function")) 
})
