# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("analysis_wordcloud_from_flows works", {
  expect_true(inherits(analysis_wordcloud_from_flows, "function")) 
})
