# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("indicator_cross_donor_systemic_destination_alignment works", {
  expect_true(inherits(indicator_cross_donor_systemic_destination_alignment, "function")) 
})
