# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("analysis_competitive_intel_matrix works", {
  expect_true(inherits(analysis_competitive_intel_matrix, "function")) 
})
