# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("analysis_donor_network_metrics works", {
  expect_true(inherits(analysis_donor_network_metrics, "function")) 
})
