# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_location_heatmap works", {
  expect_true(inherits(plot_location_heatmap, "function")) 
})
