# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("plot_donor_cluster_coverage works", {
  expect_true(inherits(plot_donor_cluster_coverage, "function")) 
})
