# WARNING - Generated by {fusen} from dev/flat_dev_1_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("filter_flows_for_indicators works", {
  expect_true(inherits(filter_flows_for_indicators, "function")) 
})
