# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("indicator_recipient_systemic_diversification works", {
  expect_true(inherits(indicator_recipient_systemic_diversification, "function")) 
})
