# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_llm_response works", {
  expect_true(inherits(clean_llm_response, "function")) 
})
