# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Fit a simple Funding Opportunity Model (logistic)
#'
#' Fits a logistic regression to predict whether a donor will fund a recipient
#' in year t+1 based on features prepared by `prepare_opportunity_dataset()`.
#'
#' Label construction: response = 1 if total_amount > 0 in year t+1 for 
#' same donor-recipient.
#'
#' @param features Dataframe produced by `analysis_prepare_opportunity_dataset()`.
#' @param min_year Minimum year to use for training (filters older data).
#'
#' @return A glm object (binomial) and the training frame 
#' (list with components model, data).
#' @importFrom dplyr group_by arrange lead left_join
#' @export
#' @examples
#' features <- analysis_prepare_opportunity_dataset(flows)$data
#' model_results <- analysis_fit_opportunity_model(features , min_year = NULL)
#' print(model_results$plot)
#'
analysis_fit_opportunity_model <- function(features, min_year = NULL) {

  df <- features
  if (!is.null(min_year))
    df <- df |> dplyr::filter(year >= min_year)
  
  # create response: whether there is funding next year
  next_year <- df |>
    dplyr::select(donor, recipient, year, total_amount) |>
    dplyr::rename(total_next = total_amount) |>
    dplyr::mutate(year = year - 1)
  
  train <- df |>
    dplyr::left_join(next_year, by = c("donor", "recipient", "year")) |>
    dplyr::mutate(opportunity = ifelse(!is.na(total_next) &
                                         total_next > 0, 1, 0)) |>
    dplyr::select(
      donor,
      recipient,
      year,
      opportunity,
      total_amount,
      pct_growth,
      avg_decision_month,
      crisis_flag,
      max_cluster_share
    )
  
  # drop rows with missing predictors
  train <- train |> stats::na.omit()
  
  if (nrow(train) < 50) {
    warning("Fewer than 50 training rows - model may be unstable.")
  }
  
  # fit a simple logistic model
  model <- stats::glm(
    opportunity ~ total_amount + pct_growth + avg_decision_month + crisis_flag + max_cluster_share,
    data = train,
    family = stats::binomial(link = "logit")
  )
  
  train$predicted_prob <- predict(model, newdata = train, type = "response")

  plot <- ggplot2::ggplot(train, 
                ggplot2::aes(x = predicted_prob, fill = factor(opportunity))) +
  ggplot2::geom_density(alpha = 0.5) +
  ggplot2::scale_y_continuous(
      labels = scales::label_number(scale_cut = scales::cut_short_scale())
    ) +
  ggplot2::scale_x_continuous(
      labels = scales::label_number(scale_cut = scales::cut_short_scale())
    ) +
  ggplot2::labs(title = "Ability to forecast potential funding streams based on previous years",
    subtitle = "Comparing the probability score assigned by the model against the
    actual outcome \n (Funding Occurred = 1, No Funding = 0).",
       x = "Predicted Probability",
       fill = "Actual Opportunity",
    caption = paste0("The X-axis shows the **Predicted Probability**
    (a score from 0 to 1) that a donor will fund a recipient in the next year. 
    The two colored curves show the distribution of this score based on the 
    **Actual Outcome** for that relationship-year observation:  **Blue Curve
    (0: No Funding):** Represents relationships where the donor *did not* fund
    the recipient next year. Most of these probabilities should cluster near 0.
    **Red Curve (1: Funding Occurred):** Represents relationships where 
    the donor *did* fund the recipient next year. 
    Most of these probabilities should cluster near 1.",
    "\n\n",
    "**Data Source**: OCHA Financial Tracking Service (FTS) API.")) +
  unhcrthemes::theme_unhcr(grid = TRUE, axis =  TRUE, axis_title = TRUE, legend=TRUE)  
  
  result <- list(model = model,
                 train = train, 
                 plot = plot)
  return(result)
}
