# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Compute Portfolio Scores for a Recipient
#'
#' Computes a portfolio score for each donor relative to a given recipient
#' using the formula:
#'
#' Portfolio_Score = SUM( Donor_engagement *
#'                        Funding_amount *
#'                        (1 - Donor_concentration_risk) *
#'                         Strategic_alignment )
#'
#' Where:
#' - Donor_engagement = fraction of years the donor funded the recipient (0-1)
#' - Funding_amount = sum(amountUSD) from donor -> recipient
#' - Donor_concentration_risk = HHI of donor across destinations (0-1)
#' higher = more concentrated implies more risk
#' - Strategic_alignment = share of donor funding to the recipient's primary
#' GlobalCluster (0-1) - best-effort derived
#'
#' Assumptions & notes:
#' - `recipient` is matched against `destinationObjects.name`
#' (destination type "Location" or "Organization" or "Plan").
#' - strategic alignment is computed by comparing GlobalCluster names present in
#'  destinationObjects for the recipient vs donor.
#' - HHI is calculated per donor across all destination names (locations/plans).
#'
#' @param flows Dataframe `flows` as documented (must include sourceObjects,
#' destinationObjects, amountUSD, budgetYear).
#' @param recipient_name Character scalar - recipient destination name to score
#' donors for (match exactly).
#' @param top_n Optional integer - return only top N donors by portfolio score
#'  (default NULL = all).
#'
#' @return Tibble with columns: donor, donor_engagement, funding_amount,
#' donor_concentration_risk, strategic_alignment, Portfolio_Score
#' @importFrom dplyr select filter group_by summarise mutate arrange desc left_join pull rename n_distinct
#' @importFrom tidyr unnest
#' @importFrom purrr map_chr map_lgl
#' @importFrom stats na.omit
#' @export
#' @examples
#' scores <- analysis_portfolio_scores(flows, 
#'                recipient_name="United Nations High Commissioner for Refugees", 
#'                           top_n = 10)
#'
#' ggplot2::ggplot(scores, ggplot2::aes(x = reorder(donor, Portfolio_Score), 
#'                                      y = Portfolio_Score)) +
#'   ggplot2::geom_col( ggplot2::aes(fill = Portfolio_Score)) +
#'   ggplot2::coord_flip() +
#'   ggplot2::labs(title = "Donor Portfolio Scores for UNHCR", 
#'        subtitle = "Measure of the combined quality, consistency, and strategic 
#'        alignment of a donor's funding relationship",
#'        x = "Donor", y = "Portfolio Score",
#'        caption = paste(
#'     "Indicator interpretation:",
#'     "The **Portfolio Score**  is calculated as: **Donor Engagement** $\\times$ 
#'     **Funding Amount** $\\times$ (1 - **Donor Concentration Risk**) $\\times$ 
#'     **Strategic Alignment**. A higher score indicates a more valuable and 
#'     reliable funding partner for the recipient.",
#'     "\n\n",
#'     
#'     " The total bar 
#'     length represents the Portfolio Score, which is driven by four components: 
#'     **Donor Engagement** (consistency of giving over time), **Funding Amount** 
#'     (total USD provided), **Donor Concentration Risk** (inverse of funding 
#'     diversification across all destinations), and **Strategic Alignment** 
#'     (share of donor funding aligned with the recipient's primary Global 
#'     Clusters).",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies key and potentially most reliable donors whose funding 
#'     relationship is both substantial and strategically aligned with the
#'     recipient's mandate. It helps the recipient organization prioritize 
#'     relationship management and provides donors with a metric to assess the
#'     quality of their long-term partnerships.", 
#'     "\n\n",
#'     "**Data Source**: OCHA Financial Tracking Service (FTS) API.")) +
#'     ggplot2::scale_y_continuous(
#'       labels = scales::label_number(scale_cut = scales::cut_short_scale())
#'     ) +
#'   unhcrthemes::theme_unhcr(grid = "X", axis =  "Y", axis_title = FALSE,
#'                            legend=FALSE)  
analysis_portfolio_scores <- function(flows,
                                      recipient_name,
                                      top_n = 10) {
  
  flows <- filter_flows_for_indicators(flows)
  # --- 1. Prepare Donors -> All Destinations (df) ---
  # Unnest sourceObjects to get donor name, filter to organizations
  df_base <- flows |>
    tidyr::unnest(sourceObjects, names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name)

  # Unnest destinationObjects to get all destinations/clusters per flow,
  # keeping the original flow structure for subsequent filtering and grouping.
  df <- df_base |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    dplyr::rename(destination = destinationObjects_name,
                  destination_type = destinationObjects_type)

  # --- 2. Donor -> Recipient Aggregated (dr) & Donor Engagement ---
  dr <- df |>
    dplyr::filter(destination == recipient_name) |>
    dplyr::group_by(donor) |>
    dplyr::summarise(
      funding_amount = sum(as.numeric(amountUSD), na.rm = TRUE),
      years_funded = dplyr::n_distinct(budgetYear[amountUSD > 0]),
      .groups = "drop"
    )

  # donor engagement (fraction of years donor active in dataset)
  donor_years <- df |>
    dplyr::group_by(donor) |>
    dplyr::summarise(total_years = dplyr::n_distinct(budgetYear),
                     .groups = "drop")

  dr <- dr |>
    dplyr::left_join(donor_years, by = "donor") |>
    dplyr::mutate(donor_engagement = ifelse(total_years > 0, years_funded / total_years, 0))

  # --- 3. Donor Concentration Risk (HHI) ---
  # HHI across all destinations (locations/plans/organizations) for each donor
  donor_hhi <- df |>
    dplyr::group_by(donor, destination) |>
    dplyr::summarise(total = sum(as.numeric(amountUSD), na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::mutate(share = total / sum(total, na.rm = TRUE)) |>
    dplyr::summarise(HHI = sum(share^2, na.rm = TRUE), .groups = "drop")

  # normalize HHI to 0-1 (already 0-1) but ensure numeric
  donor_hhi <- donor_hhi |>
    dplyr::mutate(donor_concentration_risk = pmin(pmax(HHI, 0), 1)) |>
    dplyr::select(donor, donor_concentration_risk)

  # --- 4. Strategic Alignment ---
  # Correctly extract clusters associated with the recipient
  recipient_clusters <- flows |>
    # For each flow, check if the recipient is listed in destinationObjects
    dplyr::filter(purrr::map_lgl(destinationObjects, ~ recipient_name %in% .x$name)) |>
    # From those flows, unnest to get all destination objects
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    # Filter for objects that are clusters
    dplyr::filter(destinationObjects_type %in% c("GlobalCluster", "Cluster")) |>
    # Get the unique cluster names
    dplyr::pull(destinationObjects_name) |>
    unique()

  # compute donor->cluster shares
  if (length(recipient_clusters) == 0) {
    # fallback: set strategic_alignment to donor's share to recipient / donor total (i.e., relative focus)
    donor_total <- df_base |> # Use df_base (donor->flow level) to ensure total funding is correct
      dplyr::group_by(donor) |>
      dplyr::summarise(donor_total = sum(as.numeric(amountUSD), na.rm = TRUE),
                       .groups = "drop")

    dr <- dr |>
      dplyr::left_join(donor_total, by = "donor") |>
      dplyr::mutate(strategic_alignment = ifelse(donor_total > 0, funding_amount / donor_total, 0))
  } else {
    # FIX: Use the 'df' dataframe which correctly exposes 'destination_type'
    # after the final unnesting and rename in the setup (which is 'destination_type' in the current df).
    # Wait, the column is 'destination_type' but it is *not* what's needed for the cluster filtering.
    # The error 'object 'destinationObjects_type' not found' means it was lost/renamed.
    # Let's use 'df_base' and unnest just for the cluster calculation to ensure the column name is correct.

    donor_cluster_flow <- df_base |>
      tidyr::unnest(destinationObjects, names_sep = "_")

    donor_cluster <- donor_cluster_flow |>
      dplyr::filter(destinationObjects_type %in% c("GlobalCluster", "Cluster")) |> # This column exists here
      dplyr::group_by(donor, destinationObjects_name) |>
      dplyr::summarise(total = sum(as.numeric(amountUSD), na.rm = TRUE),
                       .groups = "drop_last") |>
      dplyr::mutate(share = total / sum(total, na.rm = TRUE)) |>
      dplyr::filter(destinationObjects_name %in% recipient_clusters) |>
      dplyr::group_by(donor) |>
      dplyr::summarise(strategic_alignment = sum(share, na.rm = TRUE),
                       .groups = "drop")

    dr <- dr |>
      dplyr::left_join(donor_cluster, by = "donor") |>
      dplyr::mutate(strategic_alignment = ifelse(is.na(strategic_alignment), 0, strategic_alignment))
  }

  # --- 5. Calculate Portfolio Score ---
  res <- dr |>
    dplyr::left_join(donor_hhi, by = "donor") |>
    dplyr::mutate(
      donor_concentration_risk = ifelse(
        is.na(donor_concentration_risk),
        0,
        donor_concentration_risk
      ),
      Portfolio_Score = donor_engagement * funding_amount * (1 - donor_concentration_risk) * strategic_alignment
    ) |>
    dplyr::arrange(dplyr::desc(Portfolio_Score))

  if (!is.null(top_n))
    res <- res |> dplyr::slice_head(n = top_n)
  return(res)
}
