# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate a Word Cloud from Flow Descriptions
#'
#' Aggregates flow descriptions, cleans the text, and generates a word cloud.
#' Optionally facets the word cloud generation by budget year.
#'
#' @param flows Dataframe `flows`.
#' @param facet_by_year Logical scalar: If TRUE, returns a list of word clouds,
#'   one for each unique budget year. If FALSE, returns a single word cloud
#'   from all descriptions combined.
#' @param min_freq Integer: Minimum frequency of a word to be included in the 
#' cloud.
#' @param max_words Integer: Maximum number of words to display in the cloud.
#' @param stopwords Character vector: Additional words to remove 
#' (beyond standard English stopwords).
#' 
#' @return A wordcloud2 object (if facet_by_year=FALSE) or a named list of
#'   wordcloud2 objects (if facet_by_year=TRUE).
#'   
#' @importFrom dplyr select filter group_by summarise pull
#' @importFrom tm VCorpus VectorSource tm_map stopwords content_transformer
#' @importFrom tm removeWords removePunctuation removeNumbers stripWhitespace
#' @importFrom tm DocumentTermMatrix
#' @importFrom slam row_sums
#' @importFrom wordcloud2 wordcloud2
#' @export
#' @examples
#' analysis_wordcloud_from_flows(flows, facet_by_year = FALSE)
#' # Returns a named list of word cloud objects
#' yearly_clouds <- analysis_wordcloud_from_flows(flows, facet_by_year = TRUE)
#'
#' # To view the cloud for a specific year  
#' yearly_clouds[["2015"]]
#' yearly_clouds[["2024"]]
#' yearly_clouds[["2025"]]
analysis_wordcloud_from_flows <- function(
    flows,
    facet_by_year = FALSE,
    min_freq = 5,
    max_words = 100,
    stopwords = c("project",
                  "response",
                  "support",
                  "activities",
                  "million",
                  "allocation",
                  "reserve",
                  "usd",
                  "flow",
                  "end",
                  "start",
                  "standard",
                  "date",
                  "code",
                  "type",
                  "humanitarian",
                  "region",
                  "plan",
                  "humanitaire",
                  "r<c3><a9>ponse")) {
  
  
  # --- 1. Text Preprocessing Function ---
  process_text <- function(descriptions) {
    # 1. Create a corpus
    corpus <- tm::VCorpus(tm::VectorSource(descriptions))
    
    # 2. Text Transformation and Cleaning
    corpus <- corpus |>
      tm::tm_map(tm::content_transformer(tolower)) |>       # Convert to lowercase
      tm::tm_map(tm::removeWords, tm::stopwords("english")) |> # Remove standard English stopwords
      tm::tm_map(tm::removeWords, tm::stopwords("french")) |> # Remove standard French stopwords
      tm::tm_map(tm::removeWords, stopwords) |>             # Remove custom stopwords
      tm::tm_map(tm::removePunctuation) |>                 # Remove punctuation
      tm::tm_map(tm::removeNumbers) |>                     # Remove numbers
      tm::tm_map(tm::stripWhitespace)                      # Remove extra whitespace
    
    # 3. Create Term Document Matrix and convert to frequency table
    tdm <- tm::DocumentTermMatrix(corpus)
    freq <- slam::row_sums(tdm, na.rm = TRUE)
    
    # Get word frequencies
    freq_df <- data.frame(
      word = colnames(tdm),
      freq = as.numeric(colSums(as.matrix(tdm))),
      row.names = NULL
    ) |>
      dplyr::arrange(dplyr::desc(freq)) |>
      dplyr::filter(freq >= min_freq) |>
      dplyr::slice_head(n = max_words)
    
    return(freq_df)
  }
  
  # --- 2. Data Preparation and Grouping ---
  df_text <- flows |>
    dplyr::select(description, budgetYear) |>
    dplyr::filter(!is.na(description), description != "")
  
  # --- 3. Generate Word Cloud(s) ---
  
  if (facet_by_year) {
    
    # Group by year and aggregate descriptions
    df_yearly <- df_text |>
      dplyr::group_by(budgetYear) |>
      dplyr::summarise(all_descriptions = paste(description, collapse = " "), .groups = "drop")
    
    wordcloud_list <- list()
    
    for (i in 1:nrow(df_yearly)) {
      year <- df_yearly$budgetYear[i]
      desc <- df_yearly$all_descriptions[i]
      
      freq_df <- process_text(desc)
      
      # Generate interactive word cloud for the year
      wordcloud_list[[as.character(year)]] <- wordcloud2::wordcloud2(
        data = freq_df,
        size = 0.7,
        shape = 'circle',
        rotateRatio = 0.5,
        ellipticity = 0.8
      )
    }
    
    return(wordcloud_list)
    
  } else {
    
    # Single word cloud for all descriptions
    all_descriptions <- paste(df_text$description, collapse = " ")
    freq_df <- process_text(all_descriptions)
    
    # Generate interactive word cloud
    return(wordcloud2::wordcloud2(
      data = freq_df,
      size = 0.7,
      shape = 'circle',
      rotateRatio = 0.5,
      ellipticity = 0.8
    ))
  }
}
