# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor Lifecycle Stage Scoring
#'
#' Assigns donors to lifecycle stages:
#'  1) Prospect (alignment > 0.7, no funding)
#'  2) New Partner (1-2 years funding)
#'  3) Growing Partner (increasing amounts, multiple sectors)
#'  4) Strategic Partner (multi-year, flexible funding)
#'  5) Legacy Partner (10+ years, co-design initiatives)
#'
#' Uses flows to compute engagement_frequency, funding_trend (slope), multiyear_share proxy, and partnership_complexity proxy,
#' scoped to a specific recipient organization.
#'
#' @param flows Dataframe `flows`.
#' @param alignment_df Optional tibble with donor alignment scores (donor, alignment_score 0-1).
#' @param recipient_name Character: The name of the recipient organization to filter the flows by.
#'
#' @return Tibble with donor, metrics and stage (factor).
#' @importFrom dplyr select group_by summarise mutate arrange desc left_join n_distinct
#' @importFrom tidyr unnest
#' @importFrom stats lm coef
#' @export
#' @examples
#' recipient_name <- "United Nations High Commissioner for Refugees"
#' stages <- analysis_donor_lifecycle_stage(flows, recipient_name= recipient_name )
#'
#' ggplot2::ggplot(stages, ggplot2::aes(x = stage)) +
#'   ggplot2::geom_bar( ggplot2::aes(fill = stage)) +
#'   ggplot2::coord_flip() +
#'   ggplot2::labs(title = paste0("Donor Lifecycle Stages for ", recipient_name),
#'        subtitle = "Based on their historical funding behavior, complexity 
#'        of partnership, and alignment",
#'        x = "",
#'        y = "Number of Donors",
#'        caption = paste(
#'     "Indicator interpretation:",
#'     "This visualization segments donors into specific **Lifecycle Stages** . 
#'     This framework helps tailor engagement strategies to maximize potential 
#'     and retention. The stages represent a progression in the relationship 
#'     quality and maturity: ", 
#'     "**Prospect:** High potential alignment, but hasn't provided funding yet 
#'     (highest priority for first outreach). ", 
#'     " **New Partner:** Recently started funding (1-2 years), establishing the 
#'     relationship.",
#'     " **Growing Partner:** Demonstrates increasing funding trends and engages 
#'     across multiple sectors (focus on deepening the partnership). ",
#'     "**Strategic Partner:** Provides multi-year or flexible funding and shows
#'     high strategic alignment (focus on co-design and long-term goals). ",
#'     "**Legacy Partner:** Long-term partners (10+ years of funding), 
#'     foundational to our operations. ",
#'     "**Maintenance:** Donors that do not fit the criteria for active 
#'     growth stages (focus on efficient retention).",
#'     "\n\n",
#'     
#'     "**Data Source**: OCHA Financial Tracking Service (FTS) API Data."
#' )) +
#'   unhcrthemes::theme_unhcr(grid = "X", axis = "Y", axis_title = TRUE, 
#'                            legend=FALSE)   
analysis_donor_lifecycle_stage <- function(flows, alignment_df = NULL, recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  # --- 1. Base Unnesting and Filtering ---
  df <- flows |>
    tidyr::unnest(sourceObjects, names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    dplyr::rename(destination = destinationObjects_name, dest_type = destinationObjects_type) |>
    dplyr::mutate(amountUSD = as.numeric(amountUSD))
  
  # --- 2. Filter by Recipient Name (NEW STEP) ---
  if (!is.null(recipient_name)) {
    # If the function is scoped to a specific recipient, filter the data
    df <- df |>
      dplyr::filter(destination == recipient_name)
    
    if (nrow(df) == 0) {
      warning("No flows found for the specified recipient: ", recipient_name)
      return(tibble::tibble(donor = character(), stage = factor()))
    }
  }
  
  # --- 3. Compute Metrics (Scoped to filtered DF) ---
  
  # engagement frequency = years with any funding
  engagement <- df |>
    dplyr::group_by(donor) |>
    dplyr::summarise(years = dplyr::n_distinct(budgetYear), 
                     total_amount = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop")
  
  # funding trend: slope of amount per year (aggregate)
  trend <- df |>
    dplyr::group_by(donor, year = as.integer(budgetYear)) |>
    dplyr::summarise(year_amount = sum(amountUSD, na.rm = TRUE), .groups = "drop") |>
    dplyr::group_by(donor) |>
    dplyr::summarise(funding_trend = tryCatch({
      fit <- stats::lm(year_amount ~ year)
      coef(fit)[["year"]]
    }, error = function(e) NA_real_), .groups = "drop")
  
  # multiyear_share proxy: flows with flowType == "Parked" or parentFlowId present -> assume multiyear
  multi <- df |>
    dplyr::group_by(donor) |>
    dplyr::summarise(multiyear_share = sum(ifelse(flowType %in% c("Parked"), as.numeric(amountUSD), 0), na.rm = TRUE) / sum(as.numeric(amountUSD), na.rm = TRUE), .groups = "drop")
  
  # partnership_complexity proxy: number of distinct destination types or sectors engaged
  # Note: Since we filtered by recipient_name, the complexity will be 1 (the recipient itself)
  # unless the data structure allows for multiple sub-destinations per flow. 
  # We keep the original logic, which counts distinct destinations.
  complexity <- df |>
    dplyr::group_by(donor) |>
    dplyr::summarise(partnership_complexity = dplyr::n_distinct(destination), .groups = "drop")
  
  # --- 4. Final Join and Stage Assignment ---
  res <- engagement |>
    dplyr::left_join(trend, by = "donor") |>
    dplyr::left_join(multi, by = "donor") |>
    dplyr::left_join(complexity, by = "donor")
  
  # alignment: if provided, merge; otherwise set 0.5 default
  if (!is.null(alignment_df)) res <- res |> dplyr::left_join(alignment_df, by = "donor") else res <- res |> dplyr::mutate(alignment_score = 0.5)
  
  # stage rules (heuristic)
  res <- res |>
    dplyr::mutate(
      stage = dplyr::case_when(
        alignment_score > 0.7 & total_amount == 0 ~ "Prospect",
        years <= 2 & total_amount > 0 ~ "New Partner",
        funding_trend > 0 & partnership_complexity > 3 ~ "Growing Partner",
        multiyear_share >= 0.2 & alignment_score >= 0.6 ~ "Strategic Partner",
        years >= 10 ~ "Legacy Partner",
        TRUE ~ "Maintenance"
      )
    )
  res$stage <- factor(res$stage, levels = c("Prospect", "New Partner", "Growing Partner", "Strategic Partner", "Legacy Partner", "Maintenance"))
  
  return(res)
}
