# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Systemic: Network Density and Granularity Insights
#'
#' Calculates key metrics for the funding network structure, including overall density,
#' density over time (by year), and the granularity (density of core links vs. total links).
#'
#' @param flows A dataframe including `sourceObjects`, `destinationObjects`, and `budgetYear`.
#' @param core_threshold Numeric: Minimum funding amount (USD) for a link to be considered "Core". Default is 100000 USD.
#'
#' @return A tibble with key network metrics: Overall Density, Density by Year, Core Density, and Granularity.
#' @importFrom dplyr filter summarise n_distinct rename group_by mutate ungroup
#' @importFrom tidyr unnest 
#' @importFrom tibble tibble
#' @export
#' @examples
#' result <- analysis_systemic_network_insights(flows)
#' print(result$plot)
analysis_systemic_network_insights <- function(flows, core_threshold = 100000) {

  flows <- filter_flows_for_indicators(flows)
  # --- 1. Data Preparation ---
  df <- flows |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::mutate(
      amountUSD = as.numeric(amountUSD),
      link_id = paste(donor, recipient, sep = "->")
    )
  
  if (nrow(df) == 0) {
    return(tibble::tibble(
      Metric = character(), Value = numeric(), Description = character()
    ))
  }

  # --- 2. Overall Network Metrics (Total System) ---
  n_donors_total <- dplyr::n_distinct(df$donor)
  n_recipients_total <- dplyr::n_distinct(df$recipient)
  n_links_total <- dplyr::n_distinct(df$link_id)
  max_links_total <- n_donors_total * n_recipients_total
  
  overall_density <- n_links_total / max_links_total

  # --- 3. Core Network Metrics (System Granularity) ---
  core_links_df <- df |>
    dplyr::group_by(link_id) |>
    dplyr::summarise(total_link_amount = sum(amountUSD, na.rm = TRUE), .groups = "drop") |>
    dplyr::filter(total_link_amount >= core_threshold)
  
  n_core_links <- nrow(core_links_df)
  core_density <- n_core_links / max_links_total
  
  # Granularity: Ratio of core links to all existing links
  granularity <- n_core_links / n_links_total
  
  # --- 4. Time Trend Analysis (Density by Year) ---
  density_by_year <- df |>
    dplyr::filter(!is.na(budgetYear)) |>
    dplyr::group_by(year = as.integer(budgetYear)) |>
    dplyr::summarise(
      n_donors_y = dplyr::n_distinct(donor),
      n_recipients_y = dplyr::n_distinct(recipient),
      n_links_y = dplyr::n_distinct(link_id),
      max_links_y = n_donors_y * n_recipients_y,
      Density_by_Year = n_links_y / max_links_y,
      .groups = "drop"
    ) |>
    dplyr::select(year, Density_by_Year)

  # --- 5. Compile Results ---
  results_summary <- tibble::tibble(
    Metric = c("Overall Density", "Core Density", "Granularity"),
    Value = c(overall_density, core_density, granularity),
    Description = c(
      "Ratio of unique Donor-Recipient links to all possible links (Total System).",
      paste0("Density based only on links that exceed the $", scales::comma(core_threshold), " threshold (Core System)."),
      "Ratio of Core Links to Total Existing Links (measures concentration of funding significance)."
    )
  )
  
  plot <- ggplot2::ggplot(density_by_year, ggplot2::aes(x = year, y = Density_by_Year)) +
      ggplot2::geom_line(color = "#4361EE", size = 1.2) +
      ggplot2::geom_point(color = "#4361EE", size = 3) +
      ggplot2::geom_smooth(method = "lm", se = FALSE, linetype = "dashed", 
                  color = "grey50") +
      ggplot2::scale_y_continuous(labels = scales::percent, 
                                  limits = c(0, 
                max(density_by_year$Density_by_Year) * 1.1)) +
      ggplot2::scale_x_continuous(breaks = unique(density_by_year$year)) +
      ggplot2::labs(
        title = "Evolution of Funding Network Connectivity (Donor-Recipient Density)",
        subtitle = "Tracking the percentage of possible donor-recipient links that 
        were actually funded each year.",
        x = "Year",
        y = "Network Density (%)",
        caption = paste0(
        "Indicator interpretation:",
        "This visualization tracks the **Network Density** of the funding ecosystem
        over time. Density is a measure of **connectivity**: it represents the
        percentage of all theoretically possible unique donor-to-recipient
        relationships that actually received funding in a given year. 
        The dashed line shows the long-term trend.",
        "\n\n",
        
        "An **increasing density trend** suggests the ecosystem is becoming more
        distributed and interconnected, which may reduce risk reliance on a few key
        links. A **decreasing density trend** suggests the network is retracting or
        consolidating. 
        This helps us assess the maturity and fragmentation of the funding system.", 
        "\n\n",
        
        "**Data Source**: OCHA Financial Tracking Service (FTS) API.")  ) +
      unhcrthemes::theme_unhcr(
        grid = "Y",
        axis = TRUE,
        axis_title = TRUE,
        legend = FALSE
      )
  
  result <-list(
    Summary_Metrics = results_summary,
    Density_Trend = density_by_year,
    plot = plot
  )
  return(result)
}
