# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor Segmentation (Priority Matrix)
#'
#' Classify donors into priority segments:
#'  - Strategic Stars (High priority, under-resourced)
#'  - Core Partners (High priority, well-resourced)
#'  - Emerging Opportunities (Medium priority, growth potential)
#'  - Maintenance Accounts (Low priority, stable)
#'  - Divestment Candidates (Low priority, declining)
#'
#' Uses Engagement_Index, Alignment_Index, Growth_Potential computed from flows.
#'
#' @param flows Dataframe `flows`.
#' @param recipient_name Character name of our org (to compute "under-resourced" signals).
#'
#' @return Tibble with donor and assigned segment plus Resource_Allocation_Score.
#' @importFrom dplyr select group_by summarise mutate left_join
#' @export
#' @examples
#' recipient_name <-  "United Nations High Commissioner for Refugees"
#' segments <- analysis_donor_segmentation(flows, recipient_name)|>
#'   dplyr::filter(!is.na(total)) |> 
#'   dplyr::arrange(desc(total)) |>
#'   dplyr::slice_head(n = 20)
#'
#' label_data_top_donors <- segments |>
#'   dplyr::filter(!is.na(total)) |>  
#'   dplyr::arrange(desc(total)) |>
#'   dplyr::slice_head(n = 20)|>
#'   dplyr::mutate(donor = stringr::str_wrap(donor,
#'                                            width = 45))
#'
#' ggplot2::ggplot(segments, ggplot2::aes(x = Strategic_Priority,
#'                      y = Resource_Allocation_Score, 
#'                      color = segment,
#'                      size = total)) +
#'   ggplot2::geom_point(alpha = 0.7) +
#'   ggrepel::geom_text_repel(
#'     data = label_data_top_donors,
#'     ggplot2::aes(label = donor),  
#'     size = 3.5,
#'     segment.color = 'grey50',
#'     min.segment.length = 0,
#'     box.padding = 0.5,
#'     max.overlaps = Inf  ) +
#'   ggplot2::scale_size_continuous(labels = scales::label_number(
#'     scale_cut = scales::cut_short_scale())) +
#'   ggplot2::scale_y_continuous(labels = scales::label_number(
#'     scale_cut = scales::cut_short_scale()),
#'     n.breaks = 5) +
#'   ggplot2::scale_x_continuous(labels = scales::label_number(
#'     scale_cut = scales::cut_short_scale())) +
#'   ggplot2::labs(title = paste0("Donor Segmentation for ",  recipient_name),
#'        subtitle = "Combined value of the relationship based on 
#'        **Donor Engagement**, **Alignment Index**, and **Growth Potential** in 
#'        relation with funding history",
#'        x = "Strategic Priority",
#'        y = "Resource Allocation Score",
#'        color = "Segment",
#'        caption = paste0(
#'     "Indicator interpretation:",
#'     "For **Strategic Priority (X-axis):** Higher means a more valuable or 
#'     promising relationship.",
#'     "The **Resource Allocation Score (Y-axis):** is an indicator of whether the
#'     donor is 'under-resourced'. It is calculated as Strategic Priority divided
#'     by the total historical funding (total). Higher scores suggest the donor has
#'     high priority but currently receives relatively low engagement effort.",
#'     "The size of the bubble reflects the **Total Funding Amount** to all 
#'     destinations, showing the donor's overall financial capacity.",
#'     "\n\n",
#'     "Each bubble represents a donor, classified into a segment based on its 
#'     position on the matrix.",
#'     "This **Donor Segmentation Matrix** classifies donors into five categories
#'     based on two calculated scores:",
#'     "1. **Strategic Stars (Top-Right, High Y):** High Strategic Priority, but 
#'     currently under-resourced by our organization (high potential for increased
#'     funding/engagement).",
#'     "2. **Core Partners (Right, Lower Y):** High Strategic Priority and already
#'     well-resourced (maintain stable, high-value relationship).",
#'     "3. **Emerging Opportunities (Middle):** Medium Strategic Priority and good
#'     growth potential (focus on growth).",
#'     "4. **Divestment Candidates (Bottom-Left):** Low Strategic Priority 
#'     (low returns on effort).",
#'     "5. **Maintenance Accounts (Bottom-Right, High Total):** Lower Strategic 
#'     Priority, but historically large and stable contributors (focus on stable
#'     retention and minimizing effort).",
#'     "\n\n",
#'     "**Data Source**: OCHA Financial Tracking Service (FTS) API.")) +
#'   unhcrthemes::theme_unhcr(grid = TRUE, axis =  FALSE, axis_title = TRUE, legend=TRUE)  
analysis_donor_segmentation <- function(flows, recipient_name) {

  
  flows <- filter_flows_for_indicators(flows)
  # --- 1. Prepare Base Data (Donor -> Destination) ---
  df <- flows |>
    dplyr::mutate(destinationObjects2 = destinationObjects) |>
    tidyr::unnest(destinationObjects,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location") |>
    dplyr::rename(destination = destinationObjects_name) |>
    tidyr::unnest(sourceObjects,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects2,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(destinationObjects2_type == "Organization")|>
    dplyr::mutate(amountUSD = as.numeric(amountUSD))|>
    dplyr::rename(recipient = destinationObjects2_name) 
  
  # --- 2. Filter by Recipient Name  ---
  # If recipient_name is provided, filter the flows.
  # Note: The original 'recipient' column name is now 'destination'.
  if (!is.null(recipient_name)) {
    df <- df |>
      dplyr::filter(recipient == recipient_name)
    
    if (nrow(df) == 0) {
      warning("No flows found for the specified recipient/destination: ", recipient_name)
      return(list(graph = NULL, donor_metrics = NULL, destination_metrics = NULL))
    }
    
    # If filtered to one destination, we don't need 'top_n' for destinations, 
    # but we still calculate donor metrics based on the filtered edges.
  }
  
   # compute engagement index (years funded normalized), alignment proxy (share to recipient_name sectors), growth potential (trend)
  engagement <- df |>
    dplyr::group_by(donor) |>
    dplyr::summarise(years = dplyr::n_distinct(budgetYear), total = sum(amountUSD, na.rm = TRUE), .groups = "drop") |>
    dplyr::mutate(engagement_index = scales::rescale(years, to = c(0,1)))
  
  # alignment proxy: fraction of donor funding into destinations where recipient_name also works (same destination names)
  our_dests <- df |>
    dplyr::pull(destination) |> unique()
  
  
  if (length(our_dests) == 0) {
    alignment_df <- engagement |> dplyr::mutate(alignment_index = 0.5)
  } else {
    donor_to_our <- df |>
      dplyr::group_by(donor) |>
      
      dplyr::summarise(our_overlap = sum(amountUSD[destination %in% our_dests],
                                         na.rm = TRUE),
                       donor_total = sum(amountUSD, na.rm = TRUE),
                       .groups = "drop") |>
      
      dplyr::mutate(alignment_index = ifelse(donor_total>0, our_overlap / donor_total, 0))
    alignment_df <- donor_to_our |> dplyr::select(donor, alignment_index)
  }
  
  # growth potential: slope of funding over years
  trend <- df |>
    dplyr::group_by(donor, year = as.integer(budgetYear)) |>
    dplyr::summarise(amt = sum(amountUSD, na.rm = TRUE), .groups = "drop") |>
    dplyr::group_by(donor) |>
    dplyr::summarise(growth = tryCatch({coef(lm(amt ~ year))["year"]}, error = function(e) NA_real_), .groups = "drop") |>
    dplyr::mutate(growth_potential = scales::rescale(growth, to = c(0,1)))
  
  seg <- engagement |>
    dplyr::left_join(alignment_df, by = "donor") |>
    dplyr::left_join(trend, by = "donor") |>
    dplyr::mutate(
      alignment_index = ifelse(is.na(alignment_index), 0.5, alignment_index),
      growth_potential = ifelse(is.na(growth_potential), 0, growth_potential),
      Strategic_Priority = engagement_index * alignment_index * growth_potential,
      Resource_Allocation_Score = Strategic_Priority / (1 + total)  # normalize by current spend to identify under-resourced
    ) |>
    dplyr::mutate(
      segment = dplyr::case_when(
        Strategic_Priority >= quantile(Strategic_Priority, 0.9, na.rm = TRUE) &
          Resource_Allocation_Score > quantile(Resource_Allocation_Score, 0.5, na.rm = TRUE) ~ "Strategic Stars",
        Strategic_Priority >= quantile(Strategic_Priority, 0.7, na.rm = TRUE) ~ "Core Partners",
        Strategic_Priority >= quantile(Strategic_Priority, 0.4, na.rm = TRUE) ~ "Emerging Opportunities",
        Strategic_Priority < quantile(Strategic_Priority, 0.4, na.rm = TRUE) & total > median(total, na.rm = TRUE) ~ "Maintenance Accounts",
        TRUE ~ "Divestment Candidates"
      )
    )
  return(seg)
}
