# WARNING - Generated by {fusen} from dev/flat_dev_4_analysis.Rmd: do not edit by hand # nolint: line_length_linter.

#' Competitive Intelligence Matrix
#'
#' Computes our organization's competitive position across sectors using:
#'  - Market_share = Our_funding_in_sector / Total_sector_funding
#'  - Growth_differential = Our_growth - Average_peer_growth
#'  - Funding_diversity = 1 - HHI(our_funding_sources)
#'  - Peer_encroachment = sum(peer_growth_in_our_core_sectors)
#'
#' @param flows Dataframe `flows`.
#' @param recipient_name Character name of our organization as appears
#'  in destinationObjects.name (type Organization).
#' @param peers Optional character vector of peer organization names. 
#' If NULL peers are all other organizations in destinationObjects.
#'
#' @return Tibble with sector-level and aggregated competitive indicators
#'  and a composite Competitive_Position score.
#' @importFrom dplyr filter group_by summarise left_join mutate arrange desc n_distinct pull
#' @importFrom tidyr unnest
#' @export
#' @examples
#' recipient_name <- "United Nations High Commissioner for Refugees"
#'
#' matrix_data <- analysis_competitive_intel_matrix(flows,
#'                                               recipient_name,
#'                                               peers = NULL)
#' ggplot2::ggplot(matrix_data, ggplot2::aes(x = market_share, 
#'                                           y = growth_differential)) +
#'   ggplot2::geom_point(
#'     ggplot2::aes(size = our_funding, color = sector), alpha = 0.7) +
#'   ggplot2::geom_text(
#'     ggplot2::aes(label = sector),
#'             vjust = 1,
#'             hjust = 1,
#'             size = 3) +
#'   ggplot2::scale_y_continuous(labels = scales::label_number(
#'     scale_cut = scales::cut_short_scale())) +
#'   ggplot2::scale_x_continuous(labels = scales::label_number(
#'     scale_cut = scales::cut_short_scale())) +
#'   ggplot2::labs(
#'     title = "Competitive Intelligence Matrix",
#'     x = "Market Share",
#'     y = "Growth Differential",
#'     size = "Our Funding",
#'     caption ="**Data Source**: OCHA Financial Tracking Service (FTS) API.") +
#'   unhcrthemes::theme_unhcr(
#'     grid = FALSE,
#'     axis =  FALSE,
#'     axis_title = FALSE,
#'     legend = TRUE
#'   )  
analysis_competitive_intel_matrix <- function(flows,
                                              recipient_name,
                                              peers = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    dplyr::mutate(originaldestinationObjects = destinationObjects,
                  originalsourceObjects = sourceObjects) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c("Organization", "GlobalCluster")) |>
    dplyr::rename(dest_name = destinationObjects_name, dest_type = destinationObjects_type)
  
  # Identify sectors per flow. We'll treat rows with dest_type == sector_level as sector labels.
  # Build flow-level table mapping sector (if present) to flow. If no sector present, NA.
  # Create a combined view with source donor info
  df2 <- flows |>
    dplyr::mutate(originaldestinationObjects = destinationObjects,
                  originalsourceObjects = sourceObjects) |>
    tidyr::unnest(sourceObjects, names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    dplyr::rename(destination = destinationObjects_name, 
                  dest_type = destinationObjects_type) |>
    dplyr::mutate(amountUSD = as.numeric(amountUSD))
  
  # derive sector column
    # dput(levels(factor(df2$dest_type)))
    # dput(levels(factor(df2$dest_type)))
  df2 <- df2 |>
    dplyr::mutate(sector = dplyr::if_else(
      dest_type =="GlobalCluster",
      destination,
      NA_character_
    ))
  
  # dput(levels(factor(df2$sector)))
  # propagate sector across rows by grouping on id 
  # (flows may contain multiple destinationObjects; best-effort)
  # For simplicity aggregate by donor, destination (organization) 
  # and sector where sector not NA
  sector_flows <- df2 |>
    dplyr::filter(!is.na(sector)) |>
    dplyr::group_by(sector) |>
    dplyr::summarise(total_sector = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop")
  
  
  # our funding by sector
  # dput(levels(factor(df2$destination)))
  our_sector <- df2 |>
    dplyr::filter(destination == recipient_name) |> 
    dplyr::filter(destination == recipient_name & !is.na(sector)) |> 
    dplyr::group_by(sector) |>
    dplyr::summarise(our_funding = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop")
  
  # peers: all orgs except recipient_name if peers NULL
  if (is.null(peers)) {
    peers <- df2 |> dplyr::pull(destination) |> unique()
    peers <- setdiff(peers, recipient_name)
  }
  
  # peer growth: compute year-over-year growth in sector funding for peers
  peer_growth <- df2 |>
    dplyr::filter(destination %in% peers & !is.na(sector)) |>
    dplyr::group_by(sector, year = as.integer(budgetYear), destination) |>
    dplyr::summarise(amount = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop") |>
    dplyr::group_by(sector, destination) |>
    dplyr::arrange(year) |>
    dplyr::mutate(lag = dplyr::lag(amount),
                  growth = ifelse(!is.na(lag) &
                                    lag > 0, (amount - lag) / lag, NA_real_)) |>
    dplyr::group_by(sector) |>
    dplyr::summarise(peer_avg_growth = mean(growth, na.rm = TRUE),
                     .groups = "drop")
  
  # our_growth per sector
  our_growth <- df2 |>
    dplyr::filter(destination == recipient_name & !is.na(sector)) |>
    dplyr::group_by(sector, year = as.integer(budgetYear)) |>
    dplyr::summarise(amount = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop") |>
    dplyr::group_by(sector) |>
    dplyr::arrange(year) |>
    dplyr::mutate(lag = dplyr::lag(amount),
                  growth = ifelse(!is.na(lag) &
                                    lag > 0, (amount - lag) / lag, NA_real_)) |>
    dplyr::summarise(our_avg_growth = mean(growth, na.rm = TRUE),
                     .groups = "drop")
  
  # compute market share, growth differential, diversity (HHI) and
  # peer encroachment  market share
  market <- sector_flows |>
    dplyr::left_join(our_sector, by = "sector") |>
    dplyr::left_join(our_growth, by = "sector") |>
    dplyr::left_join(peer_growth, by = "sector") |>
    dplyr::mutate(
      our_funding = ifelse(is.na(our_funding), 0, our_funding),
      market_share = ifelse(total_sector > 0, our_funding / total_sector, NA_real_),
      growth_differential = our_avg_growth - peer_avg_growth
    )
  
  # funding diversity for our org: HHI across donors funding recipient_name
  donors_to_our <- df2 |>
    dplyr::filter(destination == recipient_name) |>
    dplyr::group_by(donor) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop") |>
    dplyr::mutate(share = total / sum(total, na.rm = TRUE))
  our_hhi <- sum((donors_to_our$share)^2, na.rm = TRUE)
  funding_diversity = 1 - our_hhi
  
  # peer encroachment: sum of peer_avg_growth in our core sectors (where our_funding > median)
  core_sectors <- market |> dplyr::filter(our_funding > median(our_funding, na.rm = TRUE)) |> dplyr::pull(sector)
  peer_encroachment <- market |> dplyr::filter(sector %in% core_sectors) |> dplyr::summarise(sum_peer_growth = sum(peer_avg_growth, na.rm = TRUE)) |> dplyr::pull(sum_peer_growth)
  
  # assemble
  market <- market |>
    dplyr::mutate(
      funding_diversity = funding_diversity,
      peer_encroachment = peer_encroachment,
      Competitive_Position = market_share + growth_differential + funding_diversity - (peer_encroachment / (length(core_sectors) + 1))
    )
  
  return(market)
}
