# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Generate Quarto HTML / PDF Country Factsheets in Batch
#'
#' This function renders the 'Country_Factsheet' Quarto template for a list of
#' countries, generating a report file for each.
#'
#' @param type either donor recipient or destination.
#' @param name name of  donor recipient or destination if NULL batch process them
#'
#' @importFrom dplyr filter select pull
#' @importFrom quarto quarto_render
#' @importFrom here here
#'
#' @return nothing, reports are generated in the specified folder.
#'
#' @export
#' @examples
#' #generate_report(type = "donor")
generate_report <- function(type="donor",
                            name=NULL) {
  
  template_path = system.file(paste0("_extension/", type,"/template.qmd"), 
                                package = "ftsAnalysis")
  ## Create the outfolder if it does not exist
  folder <- "docs/reports"
  output_dir <- here::here(folder)
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
    message("Created output directory: ", output_dir)
  }
  
  # Ensure template exists
  if (!file.exists(template_path)) {
    stop("Quarto template not found at: ", template_path, 
         ". Please check the template_path argument.")
  }
  
  flows <- filter_flows_for_indicators(flows)
  # --- Loop through each country for batch rendering ---
  if ( is.null(name)){
    if(type == "donor") {
      name <- flows |>
                tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
                dplyr::filter(sourceObjects_type == "Organization") |>
                dplyr::pull(sourceObjects_name) |>
                unlist() |>
                unique()
      # dput(names(name))
      # dput(levles(factor(name$sourceObjects_type))
    }
  
    if(type == "recipient") {
      name <- flows |>
                tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
                dplyr::filter(destinationObjects_type == "Organization") |>
                dplyr::pull(destinationObjects_name) |>
                unlist() |>
                unique()
    }
    
    
    if(type == "destination") {
      name <- flows |>
                tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
                dplyr::filter(destinationObjects_type == "Location") |>
                dplyr::pull(destinationObjects_name) |>
                unlist() |>
                unique()
    }
  } 
  
  for ( this in name) {
    
    # 2. Define Output Filename and Path
    output_filename <- paste0('ftsAnalysis-', type, '-', this, '.html')
    output_filepath <- here::here(folder, output_filename)
    
    message("Rendering report for ", name,  "...")
    
    # 3. Render the Quarto document
    tryCatch({
      quarto::quarto_render(
        input = template_path,
        output_file = output_filepath,
        # Pass parameters to the YAML header and R code chunks
        execute_params = list(name = this )
      )
      message("Successfully generated: ", output_filename)
    }, error = function(e) {
      warning("Failed to render report for ", this, ": ", e$message)
    })
  }
}
