# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor Timing Consistency Index
#'
#' This indicator measures how consistently a donor provides funding across
#' the months of the year, based on the transaction-level `date` field of
#' FTS flows. It evaluates the dispersion of monthly funding shares and scales
#' the result to a 0–1 index where higher values represent more regular and
#' predictable timing of contributions.
#'
#' @param flows A dataframe containing `sourceObjects`, `budgetMonth` (1–12),
#'  and `amountUSD`.
#' @param donors Optional dataframe with donor names.
#'
#' @return A tibble with `donor` and `Timing_Consistency` 
#'          (1 = very consistent, 0 = erratic).
#' @importFrom dplyr filter group_by summarise mutate rename
#' @importFrom  lubridate month
#' @importFrom tidyr unnest
#' @export
#' @examples
#' donors <- indicator_donor_timing_consistency(flows)
#' #table(donors$Timing_Consistency)
#' library(ggplot2)
#' ggplot(donors, aes(x = Timing_Consistency)) +
#'   geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Timing Consistency",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Measures regularity of funding distribution across month
#'     (1 = evenly spread, 0 = highly seasonal/erratic). Based on monthly 
#'     funding share dispersion.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows consistency scores. Higher values indicate predictable
#'     monthly funding patterns, lower values indicate lumpy or seasonal
#'     disbursements.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Predictable timing enables better cash flow management and program
#'     continuity, reducing operational disruptions in emergency responses.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_timing_consistency <- function(flows, donors = NULL) {
  flows <- filter_flows_for_indicators(flows)
  
  donors_df <- flows |>
    dplyr::select(sourceObjects, date, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique") |>
    dplyr::filter(type == "Organization") |>
    dplyr::rename(donor = name) |>
    dplyr::mutate(
      date = suppressWarnings(lubridate::ymd_hms(date)),
      month = lubridate::month(date)
    ) |>
    dplyr::filter(!is.na(month)) |>
    dplyr::group_by(donor, month) |>
    dplyr::summarise(
      monthly_total = sum(amountUSD, na.rm = TRUE),
      .groups = "drop_last"
    ) |>
    dplyr::mutate(
      share = monthly_total / sum(monthly_total, na.rm = TRUE)
    ) |>
    dplyr::summarise(
      sd_share = sd(share, na.rm = TRUE),
      Timing_Consistency = 1 - sd_share / 0.3,
      .groups = "drop"
    ) |>
    dplyr::mutate(
      Timing_Consistency = pmax(pmin(Timing_Consistency, 1), 0)
    )

  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df )
}
