# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Funding Consistency Index
#'
#' Calculates the proportion of years in which a donor provided funding 
#' relative to the total number of years analyzed.
#'
#' @param flows A dataframe containing FTS-style flow data with `sourceObjects`,
#'  `budgetYear`, and `amountUSD`.
#' @param donors Optional dataframe with donor names to merge results.
#'
#' @return A tibble with columns `donor` and `Funding_Consistency_Index`.
#' @importFrom dplyr select group_by summarise mutate n_distinct left_join rename
#' @importFrom purrr map_dfr
#' @importFrom tidyr unnest_wider unnest
#' @export
#' @examples
#' donors <- indicator_donor_funding_consistency(flows)
#' table(donors$Funding_Consistency_Index)
#' # library(ggplot2)
#' # ggplot(donors, aes(x = Funding_Consistency_Index)) +
#' #   geom_histogram(fill = "steelblue", color = "white") +
#' #   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#' #   labs(
#' #     title = "Distribution of Donor Funding Consistency Index",
#' #     x = "",
#' #     y = "Number of Donors",
#' #     caption = paste(
#' #     "Indicator interpretation:",
#' #     "Measures the proportion of years a donor provided funding relative to total 
#' #     years analyzed. Scores range 0-1 where 1 = consistent annual funding.",
#' #     "\n\n",
#' #     
#' #     "How to read the visualization:",
#' #     "X-axis shows consistency index values (0-1), Y-axis shows count of donors.
#' #     Bars represent frequency of donors at each consistency level.", "\n\n",
#' #     
#' #     "Humanitarian relevance:",
#' #     "Identifies reliable long-term partners vs sporadic funders, helping 
#' #     prioritize relationship building with consistent donors.", "\n\n",
#' #     
#' #     "Source: Financial Tracking Service (FTS) API."
#' #   )
#' #   )
indicator_donor_funding_consistency <- function(flows, donors = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  donors_df <- flows |>
    dplyr::select(sourceObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects) |>
    dplyr::filter(type == "Organization") |>
    dplyr::group_by(name) |>
    dplyr::summarise(
      n_years_funded = dplyr::n_distinct(budgetYear[amountUSD > 0], na.rm = TRUE),
      total_years = dplyr::n_distinct(budgetYear, na.rm = TRUE),
      Funding_Consistency_Index = ifelse(total_years > 0, 
                                         n_years_funded / total_years, NA_real_)
    ) |>
    dplyr::rename(donor = name)
  
  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df)
}
