# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Pipeline Visibility
#'
#' Measures the proportion of funding flows per destination that extend beyond 
#' the current year.
#'
#' @param flows A dataframe with `destinationObjects`, `budgetYear`, 
#' and `amountUSD`.
#' @param current_year Numeric, the current calendar year.
#' @param destinations Optional dataframe to merge.
#'
#' @return A tibble with `destination` and `Pipeline_Visibility`.
#' @importFrom dplyr filter group_by summarise mutate left_join
#' @export
#' @examples
#' destination <- indicator_destination_pipeline_visibility(flows)
#' #table(destination$Recipient_Diversification_Index)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Pipeline_Visibility)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Pipeline Visibility",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Proportion of funding flows extending beyond current year. Higher values
#'     indicate better forward visibility and multi-year planning capacity.",
#'     "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows pipeline visibility across destinations. Most destinations
#'     cluster near zero, indicating predominantly annual funding cycles.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Multi-year funding enables strategic programming, staff retention, and
#'     sustainable crisis response rather than short-term emergency patches.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_pipeline_visibility <- function(flows,
                                    current_year = as.numeric(format(Sys.Date(), "%Y")),
                                    destinations = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  dest_df <- flows |>
    dplyr::select(destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects) |>
    dplyr::filter(type == "Location") |>
    dplyr::group_by(name) |>
    dplyr::summarise(
      total_flows = dplyr::n(),
      future_flows = sum(budgetYear > current_year, na.rm = TRUE),
      Pipeline_Visibility = ifelse(total_flows > 0, future_flows / total_flows,
                                   NA_real_)
    ) |>
    dplyr::rename(destination = name)
  
  if (!is.null(destinations)) {
    dest_df <- destinations |>
     dplyr::left_join(dest_df, by = "destination")
  }
  
  return(dest_df)
}
