# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor Risk Tolerance
#'
#' Estimates donor risk tolerance as the share of funding going to:
#' - high-risk locations, and/or  
#' - new or untested recipient organisations.
#'
#' A higher score indicates a donor is more willing to take risk.
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, 
#' and `amountUSD`.
#' @param high_risk_locations Character vector of high-risk location names.
#' @param new_partners Character vector of new or emerging recipient organisations.
#'
#' @return A tibble with `donor` and `Risk_Tolerance`.
#' @importFrom dplyr filter group_by summarise mutate rename
#' @export
#' @examples
#' donor_risk <- indicator_donor_destination_risk_tolerance(
#'   flows,
#'   high_risk_locations = c("Sudan", "South Sudan", "Somalia", "Afghanistan"),
#'   new_partners        = c("Local NGO A", "Community Org B")
#' )
#'
#' # Identify top 15 donors by total contributions
#' top15 <- donor_risk |>
#'   dplyr::arrange(desc(total)) |>
#'   dplyr::slice_head(n = 15)
#'
#' donor_risk_top15 <- donor_risk |>
#'   dplyr::filter(donor %in% top15$donor) |>
#'   dplyr::mutate(
#'     donor = factor(donor, levels = top15$donor)
#'   )
#'
#' # ---- ggplot2 visualisation (viridis) ----
#' ggplot2::ggplot(
#'   donor_risk_top15,
#'   ggplot2::aes(
#'     x = donor,
#'     y = Risk_Tolerance,
#'     fill = Risk_Tolerance
#'   )
#' ) +
#'   ggplot2::geom_col() +
#'   viridis::scale_fill_viridis(
#'     name = "Risk Tolerance",
#'     option = "viridis",
#'     direction = 1,
#'     limits = c(0, 1),
#'     na.value = "grey80"
#'   ) +
#'   ggplot2::coord_flip() +
#'   ggplot2::labs(
#'     title = "Donor Risk Tolerance (Top 15 Donors)",
#'     subtitle = "Share of funding directed to high-risk locations or new partners",
#'     x = "Donor",
#'     y = "Risk Tolerance (0–1)",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Share of donor funding going to high-risk locations or new/untested partners.
#'     Higher values indicate greater risk tolerance in funding decisions.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Bar chart shows risk tolerance levels across top donors. Higher bars 
#'     indicate donors more willing to fund in complex environments or with new 
#'     partners.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies donors supporting frontline response in most challenging 
#'     contexts and investing in local capacity building through new partnerships.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   ) +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   ggplot2::theme(
#'     panel.grid.minor = ggplot2::element_blank(),
#'     legend.position = "right"
#'   )
indicator_donor_destination_risk_tolerance <- function(
  flows,
  high_risk_locations,
  new_partners
) {
  
  flows <- filter_flows_for_indicators(flows)
  
  # Clean user lists
  high_risk_locations <- tolower(trimws(high_risk_locations))
  new_partners       <- tolower(trimws(new_partners))
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    
    # ---- Unnest donor ----
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    
    # ---- Unnest destination ----
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c("Location", "Organization")) |>
    dplyr::rename(
      entity_name = destinationObjects_name,
      entity_type = destinationObjects_type
    ) |>
    
    dplyr::mutate(
      entity_clean = tolower(trimws(entity_name)),
      is_risky =
        (entity_type == "Location"     & entity_clean %in% high_risk_locations) |
        (entity_type == "Organization" & entity_clean %in% new_partners)
    ) |>
    
    dplyr::group_by(donor) |>
    dplyr::summarise(
      total = sum(amountUSD, na.rm = TRUE),
      risky = sum(amountUSD[is_risky], na.rm = TRUE),
      Risk_Tolerance = ifelse(total > 0, risky / total, NA_real_),
      .groups = "drop"
    )
  
  return(df)
}
