# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Destination: Coverage Index
#'
#' Calculates the proportion of destinations a donor supports 
#' out of the total destinations in the dataset.
#' 
#' Goal: Measures how many distinct destinations (countries/plans/sectors)
#'  a donor supports compared to the total destinations in the dataset.
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, and
#'  `amountUSD`.
#' @param donor_dest_df (optional) A dataframe of donor–destination pairs to
#'  merge results with.
#'
#' @return A tibble with `donor`, `DonorDestination_Coverage_Index`.
#' @importFrom dplyr filter distinct group_by summarise n_distinct mutate left_join rename
#' @export
#' @examples
#' donor <- indicator_donor_destination_coverage(flows)
#' #table(donor$DonorDestination_Concentration_Index)
#'
#' library(ggplot2)
#' ggplot(donor, aes(x = DonorDestination_Coverage_Index)) +
#'   geom_histogram( fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Destination Coverage Index",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Proportion of total destinations supported by donor (0 = few locations,
#'     1 = active in all locations in dataset).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows coverage breadth. Higher values indicate donors with global
#'     reach, lower values indicate regionally focused donors.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies global players vs regional specialists, informing crisis-specific
#'     partnership strategies and gap analysis.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_destination_coverage <- function(flows, donor_dest_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" ) |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::filter(amountUSD > 0) |>
    dplyr::group_by(donor) |>
    dplyr::summarise(
      supported_dest = dplyr::n_distinct(destination),
      total_dest = dplyr::n_distinct(flows$destinationObjects[[1]]$name),
      DonorDestination_Coverage_Index = supported_dest / total_dest
    )
  
  if (!is.null(donor_dest_df)) df <-dplyr::left_join(donor_dest_df, df,
                                                     by = "donor")
  return(df)
}
