# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor Systemic: Concentration Index
#'
#' Calculates the Herfindahl–Hirschman concentration index (HHI) for each donor,
#' based on the distribution of funding amounts across recipient organizations.
#' A higher value means the donor funds fewer recipients more heavily.
#' 
#' Goal: Measures how concentrated a donor’s portfolio is across recipients.
#'
#' @param flows A dataframe including `sourceObjects`, `destinationObjects`,
#'  and `amountUSD`.
#' @param donors (optional) A dataframe with donor names to merge with the
#'  results.
#'
#' @return A tibble with `donor` and `Donor_Concentration_Index` (0–1 scale).
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @importFrom tidyr unnest
#' @export
#' @examples
#' donors <- indicator_donor_systemic_concentration(flows)
#'
#' #table(donors$Donor_Concentration_Index)
#'
#' library(ggplot2)
#' ggplot(donors, aes(x = Donor_Concentration_Index)) +
#'   geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Concentration Index",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Herfindahl-Hirschman Index measuring portfolio concentration across 
#'     recipients (0 = highly diversified, 1 = focused on few recipients).",
#'     "\n\n",
#'     
#'     "How to read the visualization:",
#'     "X-axis shows concentration level. Left side indicates donors spreading
#'     funds widely, right side indicates focused funding on few partners.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Helps identify donors with broad partner networks vs specialized 
#'     relationships, informing partnership and resource mobilization strategies.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_systemic_concentration <- function(flows, donors = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  donors_df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    
    # Unnest sourceObjects first
    tidyr::unnest(sourceObjects, names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    
    # Unnest destinationObjects
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    
    # Aggregate per donor–recipient pair
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(
      total = sum(amountUSD, na.rm = TRUE),
      .groups = "drop_last"
    ) |>
    
    # Compute shares
    dplyr::mutate(
      share = total / sum(total, na.rm = TRUE)
    ) |>
    
    # Compute HHI concentration index
    dplyr::summarise(
      Donor_Concentration_Index = sum(share^2, na.rm = TRUE),
      .groups = "drop"
    ) |>
    
    # Clamp to 0–1
    dplyr::mutate(
      Donor_Concentration_Index = pmin(Donor_Concentration_Index, 1)
    )
  
  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df)
}
