# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Co-Funding Rate
#'
#' Calculates the percentage of flows where a recipient shares funding 
#' with other recipient organizations (not the sole recipient).
#'
#' @param flows A dataframe containing `destinationObjects` and `amountUSD`.
#' @param recipients Optional dataframe of recipient organizations to merge.
#'
#' @return A tibble with `recipient` and `Co_Funding_Rate`.
#' @importFrom dplyr group_by summarise mutate left_join n_distinct rename
#' @importFrom tidyr unnest
#' @export
#' @examples
#' recipients <- indicator_recipient_cofunding_rate(flows)
#' #table(recipients$Co_Funding_Rate)
#'
#' library(ggplot2)
#' ggplot(recipients, aes(x = Co_Funding_Rate)) +
#'   geom_histogram( fill = "lightgreen", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Recipients CoFunding Rate",
#'     x = "",
#'     y = "Number of Recipients",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Percentage of funding flows where recipient shares funding with other 
#'     organizations (not sole recipient). 0 = always sole recipient, 
#'     1 = always co-funded.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows co-funding frequency. Higher values indicate collaborative
#'     funding arrangements, lower values indicate standalone projects.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies organizations experienced in consortium work and coordination,
#'     crucial for complex multi-partner responses and integrated programming.", 
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_recipient_cofunding_rate <- function(flows, recipients = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  # Step 1: compute whether each flow is shared
  cofunding <- flows |>
    dplyr::select(id, destinationObjects, amountUSD) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>  
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::group_by(id) |>
    dplyr::summarise(recipient_count = n_distinct(destinationObjects_name),
                     .groups = "drop") |>
    dplyr::mutate(shared = recipient_count > 1)
  
  # Step 2: map back to each recipient
  recipients_df <- flows |>
    dplyr::select(id, destinationObjects) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |>  
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::left_join(cofunding, by = "id") |>
    dplyr::group_by(recipient) |>
    dplyr::summarise(Co_Funding_Rate = mean(shared, na.rm = TRUE),
                     .groups = "drop")
  
  # Step 3: optional merge with recipients
  if (!is.null(recipients)) {
    recipients_df <- recipients |>
      dplyr::left_join(recipients_df, by = "recipient")
  }
  
  return(recipients_df)
}
