# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Donor Diversity Index
#'
#' Calculates how diversified a destination's funding sources are
#' using the inverse Herfindahl–Hirschman Index across donors.
#' 
#' Goal: Measures how diversified funding sources are (inverse of dependency).
#' Computed using the inverse Herfindahl–Hirschman Index (1–HHI) across donors.
#'
#' @param flows A dataframe with `destinationObjects`, `sourceObjects`, 
#' and `amountUSD`.
#' @param destinations_df (optional) A dataframe of destinations to merge
#'  results with.
#'
#' @return A tibble with `destination` and `Destination_Donor_Diversity_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' destination <- indicator_destination_donor_diversity(flows)
#' #table(destination$Earmarking_Flexibility)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Donor_Diversity_Index)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Donor Diversity Index",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Inverse Herfindahl-Hirschman Index measuring donor diversification 
#'     (0=single donor dependency, 1=highly diversified funding base).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows diversification levels. Higher values indicate resilient
#'     funding ecosystems, lower values indicate vulnerability to individual
#'     donor decisions.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Diversified funding reduces crisis vulnerability to donor policy changes
#'     and ensures more stable response capacity during political shifts.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_donor_diversity <- function(flows, 
                                                  destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, sourceObjects, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" |
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    dplyr::group_by(destination, donor) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::mutate(share = total / sum(total, na.rm = TRUE)) |>
    dplyr::summarise(Destination_Donor_Diversity_Index = 1 - sum(share^2,
                                                                 na.rm = TRUE))
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df, df,
                                                       by = "destination")
  return(df)
}
