# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Funding Volume Share
#'
#' Calculates the share of total funding received by each recipient organization.
#'
#' @param flows A dataframe containing `destinationObjects` and `amountUSD`.
#' @param recipients Optional dataframe of recipient organizations to merge 
#' with the results.
#'
#' @return A tibble with columns `recipient` and `Funding_Volume_Share`.
#' @importFrom dplyr filter group_by summarise mutate left_join
#' @export
#' @examples
#' recipients <- indicator_recipient_funding_share(flows)
#' #table(recipients$Funding_Volume_Share)
#'
#' library(ggplot2)
#' # Basic histogram of Knowledge Sharing Intensity
#' ggplot(recipients, aes(x = Funding_Volume_Share)) +
#'   geom_histogram( fill = "lightgreen", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Recipients Funding Volume Share",
#'     x = "",
#'     y = "Number of Recipients",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Measures the proportion of total humanitarian funding received by each 
#'     recipient organization. Higher values indicate larger market share.", 
#'     "\n\n",
#'     
#'     "How to read the visualization:",
#'     "X-axis shows funding share (0-1), Y-axis shows recipient count. Most 
#'     recipients will have small shares, few will dominate (right tail).", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies major implementing partners and market concentration, helping 
#'     understand dependency risks and partnership opportunities.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
#'
indicator_recipient_funding_share <- function(flows, recipients = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  recipients_df <- flows |>
    dplyr::select(destinationObjects, amountUSD) |>
    tidyr::unnest(destinationObjects) |>
    dplyr::filter(type == "Organization") |>
    dplyr::group_by(name) |>
    dplyr::summarise(total_received = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop") |>
    dplyr::mutate(Funding_Volume_Share = total_received / sum(total_received,
                                                              na.rm = TRUE)) |>
    dplyr::rename(recipient = name)
  
  if (!is.null(recipients)) {
    recipients_df <- recipients |>
     dplyr::left_join(recipients_df, by = "recipient")
  }
  
  return(recipients_df)
}
