# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor-Recipient Relationship Duration Index
#'
#' Calculates the normalized duration of active funding between a donor and recipient.
#'
#' @param flows A dataframe containing `sourceObjects`, `destinationObjects`, and `budgetYear`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with columns `donor`, `recipient`, and `Relationship_Duration_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_relationship_duration(flows)
#' #table(donor_recipient$Relationship_Duration_Index)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = Relationship_Duration_Index)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Relationship Duration Index",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Normalized duration of active funding relationships between donor-recipient
#'     pairs (0=new relationship, 1=active since earliest data).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows relationship longevity across partnerships. Right-skewed 
#'     distribution indicates many new relationships, left-skewed indicates 
#'     established partnerships.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Long-term partnerships build trust, contextual understanding, and
#'     operational efficiency, leading to more effective crisis response.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_relationship_duration <- function(flows, 
                                                            donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL ) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, budgetYear) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(
      first_year = min(budgetYear, na.rm = TRUE),
      last_year = max(budgetYear, na.rm = TRUE),
      Relationship_Duration_Index = (last_year - first_year) / 
        (max(budgetYear, na.rm = TRUE) - min(budgetYear, na.rm = TRUE))
    )
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df,
                                                by = c("donor", "recipient"))
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donors  |> 
            dplyr::left_join(df |> dplyr::filter( recipient == recipient_name)
                             ,  by = c("donor"))
  }
  
  return(df)
}
