# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Knowledge Sharing Intensity
#'
#' Measures the proportion of flows mentioning collaboration, learning, or
#' assessment activities in the description.
#'
#' Goal: Quantifies the degree to which a donor’s funding supports knowledge
#' sharing, joint assessments, learning events, or coordination activities.
#'
#' @param flows A dataframe containing at least `description` and 
#'              nested `sourceObjects`.
#' @param donors (optional) A dataframe with donor names to merge with the
#'  results.
#'
#' @return A tibble with columns:
#' \describe{
#'   \item{donor}{Donor organization name.}
#'   \item{Knowledge_Sharing_Intensity}{Proportion of flows mentioning
#'         collaboration/learning/assessment (0–1).}
#' }
#'
#' @importFrom dplyr select filter group_by summarise mutate rename
#' @importFrom tidyr unnest
#' @importFrom stringr str_detect str_to_lower regex
#' @export
#' @examples
#' donors <- indicator_donor_knowledge_sharing_intensity(flows)
#' #table(donors$Knowledge_Sharing_Intensity)
#'
#' library(ggplot2)
#' # Basic histogram of Knowledge Sharing Intensity
#' ggplot(donors, aes(x = Knowledge_Sharing_Intensity)) +
#'   geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Knowledge Sharing Intensity",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Proportion of flows mentioning collaboration, learning, or assessment
#'     activities in descriptions (0 = no mention, 1 = all flows include 
#'     knowledge components).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows distribution of knowledge sharing emphasis. Higher values 
#'     indicate donors prioritizing learning and coordination in funding.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies donors supporting system-wide learning and coordination, 
#'     crucial for improving response effectiveness and accountability.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
#'
indicator_donor_knowledge_sharing_intensity <- function(flows, donors = NULL) {
  
  keywords <- "(joint|assessment|learning|coordination|evaluation|review|workshop|knowledge)"
  
  donors_df <- flows |>
    dplyr::select(sourceObjects, description) |>
    tidyr::unnest(sourceObjects, names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    dplyr::mutate(
      text = stringr::str_to_lower(description),
      mention = stringr::str_detect(text, stringr::regex(keywords))
    ) |>
    dplyr::group_by(donor) |>
    dplyr::summarise(
      Knowledge_Sharing_Intensity = mean(mention, na.rm = TRUE),
      .groups = "drop"
    )
  
  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df)
}
