# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor-Recipient Funding Growth Trend
#'
#' Estimates the linear growth (slope) of annual funding amounts from each 
#' donor to recipient.
#'
#' @param flows A dataframe containing `sourceObjects`, `destinationObjects`,
#'  `budgetYear`, `amountUSD`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with `donor`, `recipient`, and `Funding_Growth_Trend`.
#' @importFrom dplyr filter group_by summarise mutate
#' @importFrom stats lm coef
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_funding_growth(flows)
#' #table(donor_recipient$Funding_Growth_Trend)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = Funding_Growth_Trend)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Funding Growth Trend",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Linear regression slope of annual funding amounts between donor-recipient 
#'     pairs. Positive values=increasing funding, negative=decreasing funding.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows growth patterns across partnerships. Center around zero 
#'     indicates stable funding, right tail indicates expanding partnerships.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies growing vs contracting funding relationships, helping prioritize
#'     partnership development and identify successful collaboration models.", 
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_funding_growth <- function(flows, donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(
      Funding_Growth_Trend = tryCatch({
        fit <- stats::lm(amountUSD ~ budgetYear)
        stats::coef(fit)[["budgetYear"]]
      }, error = function(e) NA_real_)
    )
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df,
                                                by = c("donor", "recipient"))
  
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donor  |> 
            dplyr::filter( recipient == recipient_name) |> 
            dplyr::left_join(df,  by = c("donor"))
  }
  
  return(df)
}
