# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Earmarking Flexibility
#'
#' Computes a weighted average earmarking flexibility index per destination 
#' (Unearmarked = 1.0, Softly earmarked = 0.75, Earmarked = 0.5, Tightly earmarked = 0.25).
#'
#' @param flows A dataframe with `destinationObjects`, `amountUSD`,
#'  and `grandBargainEarmarkingType`.
#' @param destinations Optional dataframe to merge.
#'
#' @return A tibble with `destination` and `Earmarking_Flexibility`.
#'
#' @importFrom dplyr filter mutate group_by summarise left_join case_when select rename
#' @importFrom tidyr unnest
#' @export
#' @examples
#' destination <- indicator_destination_earmarking_flexibility(flows)
#' #table(destination$Earmarking_Flexibility)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Earmarking_Flexibility)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Earmarking Flexibility",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Weighted average of earmarking flexibility (1=unearmarked, 0.75=softly
#'     earmarked, 0.5=earmarked, 0.25=tightly earmarked). Higher values indicate 
#'     more flexible funding.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows flexibility scores. Higher values indicate destinations 
#'     receiving more unearmarked funding for adaptive programming.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Flexible funding enables context-responsive programming, local leadership, 
#'     and efficient resource allocation based on evolving needs rather than 
#'     rigid donor requirements.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_earmarking_flexibility <- function(flows, 
                                                         destinations = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  # flows |>
  #   dplyr::pull(grandBargainEarmarkingType) |>
  #   unlist() |>
  #   unique()
  # 
  #   "unearmarked" "softly earmarked", "earmarked", "tightly earmarked"

  # Earmarking scoring table
  scoring <- tibble::tibble(
    type = c("unearmarked", "softly earmarked", "earmarked", "tightly earmarked"),
    score = c(1.0, 0.75, 0.5, 0.25)
  )
  
  dest_df <- flows |>
    dplyr::select(destinationObjects, grandBargainEarmarkingType, amountUSD) |>
    
    # Safer unnesting — gives destinationObjects_name, destinationObjects_type, etc.
    tidyr::unnest(destinationObjects, names_sep = "_") |>
    
    # Restrict to geographic destinations
    dplyr::filter(destinationObjects_type == "Location") |>
    
    # Flatten earmarking type list-column into a simple character
    dplyr::mutate(
      earmark = purrr::map_chr(grandBargainEarmarkingType, ~
        if (is.null(.x)) NA_character_ else as.character(.x)[1]
      )
    ) |>
    
    # Join scoring table
    dplyr::left_join(scoring, by = c("earmark" = "type")) |>
    
    dplyr::group_by(destinationObjects_name) |>
    dplyr::summarise(
      Earmarking_Flexibility = weighted.mean(score, amountUSD, na.rm = TRUE)
    ) |>
    dplyr::rename(destination = destinationObjects_name)
  
  # Optionally merge with a provided destinations df
  if (!is.null(destinations)) {
    dest_df <- dplyr::left_join(destinations, dest_df, by = "destination")
  }
  
  return(dest_df)
}
