# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Destination: Geographic Focus Trend
#'
#' Evaluates whether a donor's destination concentration (HHI) is increasing or 
#' decreasing over time.
#' Goal: Captures whether a donor’s portfolio is becoming more or less geographically diversified over time (trend in HHI per year).
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, 
#' `budgetYear`, and `amountUSD`.
#' @param donor_dest_df (optional) A dataframe of donor–destination pairs to 
#' merge results with.
#'
#' @return A tibble with `donor`, `DonorDestination_Focus_Trend` (slope).
#' @importFrom dplyr  filter group_by summarise mutate rename left_join
#' @importFrom stats lm coef
#' @export
#' @examples
#' donor <- indicator_donor_destination_trend(flows)
#' #table(donor$DonorDestination_Focus_Trend)
#'
#' library(ggplot2)
#' ggplot(donor, aes(x = DonorDestination_Focus_Trend)) +
#'   geom_histogram( fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Destination Focus Trend",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Linear trend of geographic concentration over time (negative = diversifying,
#'     positive = focusing, zero = stable portfolio strategy).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows trend direction. Left of zero indicates donors broadening 
#'     geographic scope, right indicates narrowing focus.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Reveals evolving donor strategies - expansion into new crises vs 
#'     consolidation in core locations - for anticipating partnership 
#'     opportunities.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_destination_trend <- function(flows, donor_dest_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  hhi_yearly <- flows |>
    dplyr::select(sourceObjects, destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" | 
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(donor, budgetYear, destination) |>
    dplyr::summarise(amount = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::mutate(share = amount / sum(amount, na.rm = TRUE)) |>
    dplyr::summarise(HHI = sum(share^2, na.rm = TRUE))
  
  df <- hhi_yearly |>
    dplyr::group_by(donor) |>
    dplyr::summarise(
      DonorDestination_Focus_Trend = tryCatch({
        fit <- stats::lm(HHI ~ budgetYear)
        stats::coef(fit)[["budgetYear"]]
      }, error = function(e) NA_real_)
    )
  
  if (!is.null(donor_dest_df)) df <-dplyr::left_join(donor_dest_df, df,
                                                     by = "donor")
  return(df)
}
