# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Funding Growth Trend
#'
#' Computes the slope of the linear regression of funding over time
#' for each destination.
#' Goal: Detects whether funding to a destination is increasing or decreasing 
#' over time.
#'
#' @param flows A dataframe with `destinationObjects`, `budgetYear`, 
#' and `amountUSD`.
#' @param destinations_df (optional) A dataframe of destinations to merge 
#' results with.
#'
#' @return A tibble with `destination` and `Destination_Funding_Growth_Trend`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @importFrom stats lm coef
#' @export
#' @examples
#' destination <- indicator_destination_funding_trend(flows)
#' #table(destination$Destination_Funding_Growth_Trend)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Funding_Growth_Trend)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Funding Growth Trend",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Linear regression slope of annual funding over time. 
#'     Positive values=increasing funding, negative values=decreasing funding,
#'     zero=stable funding.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows growth/decline patterns. Right of zero indicates expanding
#'     crisis responses, left indicates potential donor fatigue or improving 
#'     contexts.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies crises receiving increasing attention vs. those facing funding
#'     declines despite ongoing needs, informing advocacy priorities.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_funding_trend <- function(flows, destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", 
                  names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" | 
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(destination, budgetYear) |>
    dplyr::summarise(total_year = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop_last") |>
    dplyr::summarise(
      Destination_Funding_Growth_Trend = tryCatch({
        fit <- stats::lm(total_year ~ budgetYear)
        stats::coef(fit)[["budgetYear"]]
      }, error = function(e) NA_real_)
    )
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df,
                                                       df, by = "destination")
  return(df)
}
