# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Recipient Systemic: Diversification Index
#'
#' Calculates the entropy of funding sources per recipient, indicating
#' how diversified a recipient’s funding base is across donors.
#' 
#' Goal: Measures how many donors contribute to each recipient, using entropy.
#' High entropy = diversified funding base.
#'
#' @param flows A dataframe including `sourceObjects`, `destinationObjects`,
#'  and `amountUSD`.
#' @param recipients_df (optional) A dataframe with recipient names to merge 
#' with the results.
#'
#' @return A tibble with `recipient` and `Recipient_Diversification_Index` 
#' (0–1 scale).
#' @importFrom dplyr filter group_by summarise mutate rename left_join n
#' @importFrom tidyr unnest
#' @export
#' @examples
#' recipients <- indicator_recipient_systemic_diversification(flows)
#' #table(recipients$Recipient_Diversification_Index)
#'
#' library(ggplot2)
#' ggplot(recipients, aes(x = Recipient_Diversification_Index)) +
#'   geom_histogram( fill = "lightgreen", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Recipient Diversification Index",
#'     x = "",
#'     y = "Number of Recipients",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Entropy-based measure of funding source diversification across donors. 
#'     0 = dependent on single donor,
#'     1 = perfectly diversified across many donors.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows diversification levels. Higher values indicate resilient 
#'     funding bases, lower values indicate donor concentration risks.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Diversified funding reduces vulnerability to individual donor policy 
#'     changes and enhances organizational sustainability and independence.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_recipient_systemic_diversification <- function(flows,
                                                         recipients_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    tidyr::unnest(sourceObjects, names_sep = "_") |>    
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_sep = "_") |> 
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(recipient, donor) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE), .groups = "drop_last") |>
    dplyr::mutate(share = total / sum(total, na.rm = TRUE)) |>
    dplyr::summarise(
      entropy = -sum(share * log(share), na.rm = TRUE),
      Recipient_Diversification_Index = entropy / log(dplyr::n()),
      .groups = "drop"
    ) |>
    dplyr::mutate(
      Recipient_Diversification_Index = pmin(Recipient_Diversification_Index, 1))
  
  if (!is.null(recipients_df)) {
    df <- dplyr::left_join(recipients_df, df, by = "recipient")
  }
  
  return(df)
}

