# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Funding Volatility Index
#'
#' Calculates volatility in funding for each destination across `budgetYear`,
#' using the coefficient of variation (CV) of annual totals.
#' 
#' Goal: Quantifies year-to-year variability in funding amounts for each 
#' destination.
#'
#' @param flows A dataframe including `destinationObjects`, `budgetYear`, 
#' and `amountUSD`.
#' @param destinations_df (optional) A dataframe with destination names to 
#' merge results with.
#'
#' @return A tibble with `destination` and `Destination_Funding_Volatility`
#'  (0–1, where 1 = stable).
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' destination <-indicator_destination_funding_volatility(flows)
#' #table(destination$Destination_Funding_Volatility)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Funding_Volatility)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Funding Volatility",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "1 minus coefficient of variation of annual funding (0=highly volatile,
#'     1=perfectly stable). Inverse measure of year-to-year funding
#'     unpredictability.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows volatility patterns. Higher values enable predictable 
#'     programming, lower values indicate disruptive funding fluctuations.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Funding volatility disrupts staffing, procurement, and program continuity, 
#'     reducing operational efficiency and response effectiveness.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_funding_volatility <- function(flows, 
                                                     destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c("Location")) |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(destination, budgetYear) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::summarise(
      mean_amt = mean(total, na.rm = TRUE),
      sd_amt = sd(total, na.rm = TRUE),
      cv = sd_amt / mean_amt,
      Destination_Funding_Volatility = 1 - pmin(cv, 1)
    )
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df, df,
                                                       by = "destination")
  return(df)
}
