# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Amount Stability
#'
#' Measures the stability of annual funding amounts for each recipient as 
#' 1 minus the coefficient of variation of annual totals.
#'
#' @param flows A dataframe containing `destinationObjects`, `budgetYear`, 
#' and `amountUSD`.
#' @param recipients Optional dataframe of recipient organizations to merge.
#'
#' @return A tibble with columns `recipient` and `Amount_Stability`.
#' @importFrom dplyr group_by summarise mutate left_join
#' @export
#' @examples
#'
#' recipients <- indicator_recipient_amount_stability(flows)
#' #table(recipients$Amount_Stability)
#'
#' library(ggplot2)
#' ggplot(recipients, aes(x = Amount_Stability)) +
#'   geom_histogram( fill = "lightgreen", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Recipients Amount Stability",
#'     x = "",
#'     y = "Number of Recipients",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Measures year-to-year funding stability as 1 minus coefficient of variation.
#'     1 = perfectly stable annual funding, lower values = volatile funding 
#'     patterns.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows stability scores. Higher values indicate predictable funding
#'     streams, negative values indicate high volatility (SD > mean).", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Stable funding enables long-term programming and institutional strengthening,
#'     while volatility disrupts operations and staff retention.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_recipient_amount_stability <- function(flows, recipients = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  recipients_df <- flows |>
    dplyr::select(destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects) |>
    dplyr::filter(type == "Organization") |>
    dplyr::group_by(name, budgetYear) |>
    dplyr::summarise(annual_amount = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop_last") |>
    dplyr::summarise(
      mean_amt = mean(annual_amount, na.rm = TRUE),
      sd_amt = sd(annual_amount, na.rm = TRUE),
      Amount_Stability = 1 - (sd_amt / mean_amt)
    ) |>
    dplyr::rename(recipient = name)
  
  if (!is.null(recipients)) {
    recipients_df <- recipients |>
     dplyr::left_join(recipients_df, by = "recipient")
  }
  
  return(recipients_df)
}
