# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Modality Innovation
#'
#' Calculates the percentage of funding to a destination that is Cash Transfer
#'  Programming (CTP).
#'
#' @param flows A dataframe with `destinationObjects`, `amountUSD`, and `method`.
#' @param destinations Optional dataframe to merge results with.
#'
#' @return A tibble with `destination` and `Modality_Innovation`.
#' @importFrom dplyr filter group_by summarise mutate left_join
#' @export
#' @examples
#' destination <- indicator_destination_modality_innovation(flows)
#' #table(destination $Recipient_Diversification_Index)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Modality_Innovation)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Modality Innovation",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Percentage of funding using Cash Transfer Programming (CTP) per destination.
#'     Higher values indicate greater adoption of innovative cash-based approaches.",
#'     "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows CTP adoption rates across destinations. Right-skewed 
#'     distribution indicates most destinations have low CTP usage, few are CTP 
#'     leaders.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Cash programming increases efficiency, dignity, and local market benefits.
#'     Identifies destinations where cash coordination capacity may need 
#'     strengthening.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_modality_innovation <- function(flows, 
                                                      destinations = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  dest_df <- flows |>
    dplyr::select(destinationObjects, method, amountUSD) |>
    tidyr::unnest(destinationObjects) |>
    dplyr::filter(type == "Location") |>
    dplyr::group_by(name) |>
    dplyr::summarise(
      total = sum(amountUSD, na.rm = TRUE),
      ctp = sum(amountUSD[method == "Cash Transfer Programming (CTP)"],
                na.rm = TRUE),
      Modality_Innovation = ifelse(total > 0, ctp / total, NA_real_)
    ) |>
    dplyr::rename(destination = name)
  
  if (!is.null(destinations)) {
    dest_df <- destinations |>
     dplyr::left_join(dest_df, by = "destination")
  }
  
  return(dest_df)
}
