# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Modality Balance
#'
#' Calculates the share of cash or voucher-based programming (CTP)
#' relative to all modalities within each destination.
#' 
#' Goal: Measures the balance between cash-based programming and traditional 
#' modalities, based on the method variable.
#'
#' @param flows A dataframe including `destinationObjects`, `method`, 
#' and `amountUSD`.
#' @param destinations_df (optional) A dataframe with destination names 
#' to merge results with.
#'
#' @return A tibble with `destination` and `Destination_Modality_Balance` 
#' (0–1 share of CTP).
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' destination <- indicator_destination_modality_balance(flows)
#' #table(destination$Destination_Modality_Balance)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Modality_Balance)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Modality Balance",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Share of cash-based programming (CTP) relative to all modalities (0-1).
#'     Higher values indicate greater cash modality utilization.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows CTP adoption across destinations. Most destinations cluster
#'     near zero, indicating traditional in-kind programming dominance.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Appropriate modality balance ensures efficient, dignified assistance while
#'     maintaining essential in-kind support where markets are non-functional.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_modality_balance <- function(flows, 
                                                   destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, method, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c("Location")) |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(destination, method) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::mutate(
      Destination_Modality_Balance = ifelse(
        method %in% c("Cash transfer programming (CTP)"),
        total, 0
      )
    ) |>
    dplyr::summarise(
      Destination_Modality_Balance = sum(Destination_Modality_Balance,
                                         na.rm = TRUE) /
        sum(total, na.rm = TRUE)
    )
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df, df, 
                                                       by = "destination")
  return(df)
}
