# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Recipient: Funding Trend Index
#'
#' Computes the slope of the funding trend over time for each 
#' donor–recipient pair.
#' 
#' Goal: Detects whether funding between a donor and recipient is increasing 
#' or decreasing over time (slope of linear regression).
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`,
#'  `budgetYear`, and `amountUSD`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with `donor`, `recipient`, 
#' and `DonorRecipient_Trend_Index` (slope).
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @importFrom stats lm coef
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_trend(flows)
#' #table(donor_recipient$DonorRecipient_Trend_Index)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = DonorRecipient_Trend_Index)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Trend Index",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Linear trend of funding amounts between donor-recipient pairs over time. 
#'     Positive=increasing investment, negative=phasing out partnership.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows partnership evolution patterns. Right of zero indicates 
#'     growing collaborations, left indicates declining engagements.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Reveals evolving partnership strategies - scaling successful collaborations
#'     vs exiting less effective ones - informing relationship management.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_trend <- function(flows, donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(
      DonorRecipient_Trend_Index = tryCatch({
        fit <- stats::lm(amountUSD ~ budgetYear)
        stats::coef(fit)[["budgetYear"]]
      }, error = function(e) NA_real_)
    )
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df, 
                                                by = c("donor", "recipient"))
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donor  |> 
            dplyr::filter( recipient == recipient_name) |> 
            dplyr::left_join(df,  by = c("donor"))
  }
  return(df)
}
