# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Recipient: Reciprocity Ratio
#'
#' Identifies donor–recipient pairs where both have exchanged funding
#' (each organization acts as donor and recipient at least once).
#' 
#' Goal: Checks whether a donor and recipient have mutual funding roles 
#' (both send and receive) — useful for consortia or pooled mechanisms.
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, 
#' and `amountUSD`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with `donor`, `recipient`, 
#' and `DonorRecipient_Reciprocity_Ratio` (0 or 1).
#' @importFrom dplyr filter distinct left_join rename mutate
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_reciprocity(flows)
#' #table(donor_recipient$DonorRecipient_Reciprocity_Ratio)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = DonorRecipient_Reciprocity_Ratio)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Reciprocity Ratio",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Binary indicator of mutual funding relationships where both organizations 
#'     act as donor and recipient to each other (0=one-way, 1=reciprocal).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Two bars showing proportion of one-way vs reciprocal partnerships. 
#'     Higher reciprocal values indicate collaborative funding ecosystems.",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Reciprocal funding indicates consortia, pooled funds, or collaborative 
#'     programming arrangements that enhance coordination and local ownership.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_reciprocity <- function(flows, donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  donor_recipient <- flows |>
    dplyr::select(sourceObjects, destinationObjects) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::distinct(donor, recipient)
  
  reciprocal <- donor_recipient |>
    dplyr::inner_join(
      donor_recipient |> dplyr::rename(donor = recipient, recipient = donor),
      by = c("donor", "recipient")
    ) |>
    dplyr::mutate(DonorRecipient_Reciprocity_Ratio = 1)
  
  df <- donor_recipient |>
   dplyr::left_join(reciprocal, by = c("donor", "recipient")) |>
    dplyr::mutate(DonorRecipient_Reciprocity_Ratio = ifelse(is.na(DonorRecipient_Reciprocity_Ratio), 0, 1))
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df,
                                                by = c("donor", "recipient"))
  
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donor  |> 
            dplyr::filter( recipient == recipient_name) |> 
            dplyr::left_join(df,  by = c("donor"))
  }
  
  return(df)
}
