# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Recipient: Relationship Stability Index
#'
#' Calculates how consistently a donor funds a recipient over the time series,
#' as the proportion of years with nonzero funding between the pair.
#' 
#' Goal: Measures how consistently a donor funds a recipient over time 
#' (share of active years).
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, 
#' `budgetYear`, and `amountUSD`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with `donor`, `recipient`, and `DonorRecipient_Stability_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join n_distinct
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_stability(flows)
#' #table(donor_recipient$DonorRecipient_Stability_Index)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = DonorRecipient_Stability_Index)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Stability Index",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Proportion of years with active funding between donor-recipient pairs 
#'     (0=sporadic funding, 1=consistent annual funding throughout relationship).",
#'     "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows funding consistency patterns. Higher values indicate 
#'     reliable annual partnerships, lower values indicate intermittent engagement.",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Consistent funding enables long-term programming, staff retention, and 
#'     institutional strengthening rather than project-based short-term engagements.", 
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_stability <- function(flows, donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(
      active_years = dplyr::n_distinct(budgetYear[amountUSD > 0], na.rm = TRUE),
      total_years = dplyr::n_distinct(budgetYear, na.rm = TRUE),
      DonorRecipient_Stability_Index = ifelse(total_years > 0, active_years / total_years, NA_real_)
    )
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df, 
                                                by = c("donor", "recipient"))
  
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donors  |> 
            dplyr::left_join(df |> dplyr::filter( recipient == recipient_name)
                             ,  by = c("donor"))
  }
  
  return(df)
}
