# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Dependency Index
#'
#' Calculates the share of a destination's total funding that comes
#' from its single largest donor.
#' 
#' Goal: Measures reliance on the top donor — i.e., the share of total funding
#'  coming from the largest donor.
#'
#' @param flows A dataframe including `sourceObjects`, `destinationObjects`,
#'  and `amountUSD`.
#' @param destinations_df (optional) A dataframe with destination names to 
#' merge results with.
#'
#' @return A tibble with `destination` and `Destination_Dependency_Index`
#'  (0–1, higher = more dependent).
#' @importFrom dplyr filter group_by summarise mutate rename slice_max left_join
#' @export
#' @examples
#' destination <-indicator_destination_dependency(flows)
#' #table(destination$Destination_Dependency_Index)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Dependency_Index)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Dependency Index",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Share of total funding from largest single donor (0-1). Higher values 
#'     indicate heavy reliance on one donor, creating vulnerability.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows dependency levels. Values near 1 indicate high-risk 
#'     single-donor dependencies requiring diversification strategies.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Single-donor dependency creates systemic risk - if that donor changes 
#'     priorities, entire crisis responses can be jeopardized.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_dependency <- function(flows, destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c("Location")) |>
    dplyr::rename(destination = destinationObjects_name) |>
    tidyr::unnest(sourceObjects, names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    dplyr::group_by(destination, donor) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop_last") |>
    dplyr::summarise(
      top_share = max(total, na.rm = TRUE) / sum(total, na.rm = TRUE),
      Destination_Dependency_Index = top_share
    )
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df,
                                                       df, by = "destination")
  return(df)
}
