# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Recipient: Funding Concentration Index
#'
#' Measures the share of a recipient’s total funding that comes from a 
#' specific donor.
#' 
#' Goal: Quantifies how dependent the recipient is on that donor (share of 
#' donor’s contribution among total received).
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`,
#'  and `amountUSD`.
#' @param donor_recipient_pairs (optional) A dataframe of donor–recipient pairs to merge 
#' results with.
#' @param donors (optional used if recipient_name is provided ) A dataframe with donor names to merge with the  results.  
#' @param recipient_name (optional) the name of a specific recipient to filter the results of the function  
#'
#' @return A tibble with `donor`, `recipient`, and 
#' `DonorRecipient_Concentration_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' donor_recipient <- indicator_donor_recipient_concentration(flows)
#' #table(donor_recipient$DonorRecipient_Stability_Index)
#'
#' library(ggplot2)
#' ggplot(donor_recipient, aes(x = DonorRecipient_Concentration_Index)) +
#'   geom_histogram( fill = "green", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Recipient Concentration Index",
#'     x = "",
#'     y = "Number of Donor-Recipient Pairs",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Share of recipient's total funding coming from specific donor (0-1). 
#'     Higher values indicate recipient dependency on that donor.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows dependency levels across partnerships. Values near 1 
#'     indicate critical donor dependencies requiring diversification strategies.",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies vulnerable partnerships where recipient organizations risk 
#'     severe disruption if key donors change funding priorities.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_recipient_concentration <- function(flows, donor_recipient_pairs = NULL, 
                                                            donors = NULL, 
                                                           recipient_name = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization") |>
    dplyr::rename(recipient = destinationObjects_name) |>
    dplyr::group_by(recipient, donor) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE), 
                     .groups = "drop_last") |>
    dplyr::mutate(DonorRecipient_Concentration_Index = total / sum(total, na.rm = TRUE)) |>
    dplyr::ungroup()
  
  if (!is.null(donor_recipient_pairs)) df <-dplyr::left_join(donor_recipient_pairs, df, 
                                                by = c("donor", "recipient"))
  
  
  if (!is.null(donors) && !is.null(recipient_name) && is.null(donor_recipient_pairs) ) {
      df <- donors  |> 
            dplyr::left_join(df |> dplyr::filter( recipient == recipient_name)
                             ,  by = c("donor"))
  }
  
  return(df)
}
