# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Relationship Duration Index
#'
#' Measures the duration of a donor’s funding relationship relative to the 
#' maximum possible duration.
#'
#' @param flows A dataframe containing `sourceObjects` and `budgetYear`.
#' @param donors Optional dataframe with donor names.
#'
#' @return A tibble with `donor` and `Relationship_Duration_Index`.
#' @importFrom dplyr  group_by summarise mutate left_join rename
#' @importFrom tidyr unnest
#' @export
#' @examples
#' donors <- indicator_donor_relationship_duration(flows)
#' #table(donor$Relationship_Duration_Index)
#' library(ggplot2)
#' ggplot(donors, aes(x = Relationship_Duration_Index)) +
#'   geom_histogram(binwidth = 0.05, fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Relationship Duration Index",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Measures duration of donor's funding relationship relative to maximum 
#'     possible duration. 1 = active since earliest data, 0 = new entrant.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows distribution of duration scores. Left-skewed distribution 
#'     indicates many new donors, right-skewed indicates established 
#'     relationships.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Long-term donors often have deeper contextual understanding and more 
#'     predictable funding patterns for strategic planning.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_relationship_duration <- function(flows, donors = NULL) {
   
  flows <- filter_flows_for_indicators(flows)
  
  # Global range across entire dataset
  global_min_year <- min(flows$budgetYear, na.rm = TRUE)
  global_max_year <- max(flows$budgetYear, na.rm = TRUE)
  global_range <- global_max_year - global_min_year
  
  donors_df <- flows |>
    dplyr::filter(boundary == "incoming") |> 
    dplyr::select(sourceObjects, budgetYear) |>
    tidyr::unnest(sourceObjects, names_repair = "unique") |>
    
    # FIX: after unnesting, names are simply name, type
    dplyr::filter(type == "Organization") |>
    dplyr::rename(donor = name) |>
    
    dplyr::group_by(donor) |>
    dplyr::summarise(
      first_year = min(budgetYear, na.rm = TRUE),
      last_year  = max(budgetYear, na.rm = TRUE),
      Relationship_Duration_Index = dplyr::case_when(
        is.na(first_year) | is.na(last_year) ~ NA_real_,
        global_range == 0 ~ NA_real_,
        TRUE ~ (last_year - first_year) / global_range
      ),
      .groups = "drop"
    )
  
  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df)
}
