# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Donor Retention Index
#'
#' Calculates the proportion of donors who provided funding to a destination
#' in consecutive years (repeat donors).
#' Goal: Measures the proportion of donors who continue funding a destination 
#' year after year.
#'
#' @param flows A dataframe with `destinationObjects`, `sourceObjects`, 
#' `budgetYear`, and `amountUSD`.
#' @param destinations_df (optional) A dataframe of destinations to merge
#'  results with.
#'
#' @return A tibble with `destination` and `Destination_Donor_Retention_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join arrange lag n_distinct
#' @importFrom purrr map2_dbl  
#' @export
#' @examples
#' destination <- indicator_destination_donor_retention(flows)
#' #table(destination$Destination_Donor_Retention_Index)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Donor_Retention_Index)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Donor Retention Index",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Proportion of donors who continue funding a destination year after year. 
#'     Higher values indicate loyal donor bases and sustained engagement.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows retention rates. Higher values indicate stable donor 
#'     relationships, lower values indicate high donor turnover and relationship
#'     building needs.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Donor retention reduces transaction costs, builds contextual knowledge, 
#'     and enables more effective long-term partnerships in complex crises.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_donor_retention <- function(flows, destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, sourceObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" |
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    dplyr::group_by(destination, budgetYear) |>
    dplyr::summarise(donors = list(unique(donor)), .groups = "drop") |>
    dplyr::arrange(destination, budgetYear) |>
    dplyr::group_by(destination) |>
    dplyr::mutate( 
      prev_donors = dplyr::lag(donors),
      retained = purrr::map2_dbl(donors, prev_donors, 
                                 ~ if (is.null(.y)) 0 else 
                                   length(intersect(.x, .y)) / length(.y))
    ) |>
    dplyr::summarise(Destination_Donor_Retention_Index = mean(retained,
                                                              na.rm = TRUE))
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df, 
                                                       df, by = "destination")
  return(df)
}

