# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Destination-Focused: Funding Stability Index
#'
#' Measures how stable funding amounts are for each destination over time.
#' Computed as 1 - coefficient of variation of annual funding.
#' Goal: Captures predictability of funding amounts over years (inverse of
#'  coefficient of variation).
#'
#' @param flows A dataframe with `destinationObjects`, `budgetYear`,
#'  and `amountUSD`.
#' @param destinations_df (optional) A dataframe of destinations to merge
#'  results with.
#'
#' @return A tibble with `destination` and `Destination_Funding_Stability_Index`.
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' destination <- indicator_destination_funding_stability(flows)
#' #table(destination$Destination_Funding_Stability_Index)
#'
#' library(ggplot2)
#' ggplot(destination, aes(x = Destination_Funding_Stability_Index)) +
#'   geom_histogram( fill = "red", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Destination Funding Stability Index",
#'     x = "",
#'     y = "Number of Destination",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "1 minus coefficient of variation of annual funding amounts. 
#'     1=perfectly stable, lower values=volatile funding, 
#'     negative values=high volatility (SD > mean).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows stability patterns. Higher values enable predictable 
#'     programming, negative values indicate boom-bust cycles disrupting operations.",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Funding stability enables long-term planning, staff retention, and 
#'     consistent service delivery rather than reactive emergency-only responses.",
#'     "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_destination_funding_stability <- function(flows,
                                                    destinations_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(destinationObjects, budgetYear, amountUSD) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", 
                  names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" | 
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(destination, budgetYear) |>
    dplyr::summarise(total_year = sum(amountUSD, na.rm = TRUE),
                     .groups = "drop_last") |>
    dplyr::summarise(
      mean_amt = mean(total_year, na.rm = TRUE),
      sd_amt = sd(total_year, na.rm = TRUE),
      Destination_Funding_Stability_Index = ifelse(mean_amt > 0, 
                                                   1 - (sd_amt / mean_amt),
                                                   NA_real_)
    )
  
  if (!is.null(destinations_df)) df <-dplyr::left_join(destinations_df, df,
                                                       by = "destination")
  return(df)
}
