# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Donor→Destination: Portfolio Concentration Index
#'
#' Computes how concentrated a donor's funding portfolio is across destinations,
#' using the Herfindahl–Hirschman Index (sum of squared funding shares).
#' 
#' Goal: Quantifies how concentrated (vs diversified) a donor’s funding 
#' portfolio is across destinations using the Herfindahl–Hirschman Index (HHI).
#'
#' @param flows A dataframe with `sourceObjects`, `destinationObjects`, and
#'  `amountUSD`.
#' @param donor_dest_df (optional) A dataframe of donor–destination pairs to
#'  merge results with.
#'
#' @return A tibble with `donor`, `DonorDestination_Concentration_Index`
#'          (0=diverse, 1=concentrated).
#' @importFrom dplyr filter group_by summarise mutate rename left_join
#' @export
#' @examples
#' donor <- indicator_donor_destination_concentration(flows)
#' #table(donor$DonorDestination_Concentration_Index)
#'
#' library(ggplot2)
#' ggplot(donor, aes(x = DonorDestination_Concentration_Index)) +
#'   geom_histogram( fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Destination Concentration Index",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Herfindahl-Hirschman Index measuring geographic portfolio concentration 
#'     (0 = highly diversified, 1 = focused on few locations/plans).", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "Histogram shows concentration levels. Left indicates global spread, right 
#'     indicates focused geographic operations in few crises.", "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Helps understand donor geographic strategies - specialized crisis 
#'     responders vs broad global supporters - for targeted engagement.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_destination_concentration <- function(flows,
                                                      donor_dest_df = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  df <- flows |>
    dplyr::select(sourceObjects, destinationObjects, amountUSD) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::rename(donor = sourceObjects_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location" | 
                    destinationObjects_type == "Plan") |>
    dplyr::rename(destination = destinationObjects_name) |>
    dplyr::group_by(donor, destination) |>
    dplyr::summarise(total = sum(amountUSD, na.rm = TRUE), .groups = "drop_last") |>
    dplyr::mutate(share = total / sum(total, na.rm = TRUE)) |>
    dplyr::summarise(DonorDestination_Concentration_Index = sum(share^2,
                                                                na.rm = TRUE))
  
  if (!is.null(donor_dest_df)) df <-dplyr::left_join(donor_dest_df, df, 
                                                     by = "donor")
  return(df)
}
