# WARNING - Generated by {fusen} from dev/flat_dev_2_indicator.Rmd: do not edit by hand # nolint: line_length_linter.

#' Funding Growth Trend
#'
#' Calculates the linear trend (slope) of annual funding amounts over years for
#'  each donor.
#'
#' @param flows A dataframe with `sourceObjects`, `budgetYear`, and `amountUSD`.
#' @param donors Optional dataframe with donor names.
#'
#' @return A tibble with `donor` and `Funding_Growth_Trend` (slope of funding 
#' over years).
#' @importFrom dplyr  group_by summarise mutate left_join
#' @importFrom tidyr unnest
#' @importFrom stats lm coef
#' @export
#' @examples
#' donors <- indicator_donor_funding_growth(flows)
#' #table(donors$Funding_Growth_Trend)
#' library(ggplot2)
#' ggplot(donors, aes(x = Funding_Growth_Trend)) +
#'   geom_histogram( fill = "steelblue", color = "white") +
#'   unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
#'   labs(
#'     title = "Distribution of Donor Funding Growth Trend",
#'     x = "",
#'     y = "Number of Donors",
#'     caption = paste(
#'     "Indicator interpretation:",
#'     "Linear regression slope of annual funding amounts over time. Positive 
#'     values = increasing funding, negative = decreasing funding.", "\n\n",
#'     
#'     "How to read the visualization:",
#'     "X-axis shows growth rate (USD per year), Y-axis shows donor count. Center 
#'     around zero indicates stable funding, right tail indicates growing donors.",
#'     "\n\n",
#'     
#'     "Humanitarian relevance:",
#'     "Identifies expanding vs contracting funding sources, helping target 
#'     advocacy and partnership efforts with growing donors.", "\n\n",
#'     
#'     "Source: Financial Tracking Service (FTS) API."
#'   )
#'   )
indicator_donor_funding_growth <- function(flows, donors = NULL) {
  
  flows <- filter_flows_for_indicators(flows)
  
  donors_df <- flows |>
    dplyr::select(sourceObjects, budgetYear, amountUSD) |>
    tidyr::unnest(sourceObjects) |>
    dplyr::filter(type == "Organization") |>
    dplyr::group_by(name) |>
    dplyr::summarise(
      Funding_Growth_Trend = tryCatch({
        fit <- stats::lm(amountUSD ~ budgetYear)
        stats::coef(fit)[["budgetYear"]]
      }, error = function(e) NA_real_)
    ) |>
    dplyr::rename(donor = name)
  
  if (!is.null(donors)) {
    donors_df <- donors |> dplyr::left_join(donors_df, by = "donor")
  }
  
  return(donors_df)
}
