# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Top Donors Heatmap
#'
#' Visualizes the total funding from top donors to recipient organizations
#' for a given destination.
#'
#' @param flows FTS flows dataframe
#' @param destination_name Name of the destination location to filter for
#' @param top_n Number of top donors to display (default = 5)
#'
#' @return A ggplot heatmap
#' @importFrom dplyr filter mutate group_by summarise slice_max ungroup select rename inner_join
#' @importFrom tidyr unnest
#' @importFrom stringi stri_enc_toutf8
#' @importFrom purrr map map_df
#' @export
#' @examples
#' p <- plot_destination_heatmap(flows, destination_name= "Burundi", top_n = 5)
#'
#' # getting LLm story
#' story <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini", max_tokens = 300)
#' # cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_destination_heatmap <- function(flows, destination_name, top_n = 5) {
   flows <- filter_flows_for_indicators(flows)
  # ---- STEP 1: Expand nested destination objects ----
  dest_expanded <- flows |>
    dplyr::mutate(destinationObjects2 = destinationObjects) |>
    tidyr::unnest(destinationObjects,
                  names_repair = "unique",
                  names_sep = "_")
  
  # ---- STEP 2: Filter for destination (case-insensitive) ----
  flows_loc <- dest_expanded |>
    dplyr::filter(
      destinationObjects_type == "Location",
      tolower(destinationObjects_name) == tolower(destination_name)
    )
  
  if (nrow(flows_loc) == 0) {
    warning(paste("No flows found for destination:", destination_name))
    return(
      ggplot2::ggplot() +
        ggplot2::labs(title = paste("No data for", destination_name))
    )
  }
  
  # ---- STEP 3: Expand donor and recipient orgs ----
  donors_recipient_expanded <- flows_loc |>
    tidyr::unnest(sourceObjects,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    tidyr::unnest(destinationObjects2,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(destinationObjects2_type == "Organization")
  
  # ---- STEP 4: Aggregate donor → recipient totals ----
  flow_data <- donors_recipient_expanded  |>
    dplyr::mutate(
      donor = stringi::stri_enc_toutf8(sourceObjects_name),
      recipient = stringi::stri_enc_toutf8(destinationObjects2_name)
    ) |>
    dplyr::group_by(donor, recipient) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE), .groups = "drop")
  
  if (nrow(flow_data) == 0) {
    warning("No Donor to Recipient organization flows for this destination.")
    return(ggplot2::ggplot() + ggplot2::labs(title = "No organization-level data"))
  }
  
  # ---- STEP 5: Select Top N donors ----
  top_donors <- flow_data |>
    dplyr::group_by(donor) |>
    dplyr::summarise(total = sum(total_usd), .groups = "drop") |>
    dplyr::slice_max(total, n = top_n)
  
  df_plot <- top_donors |>
    dplyr::inner_join(flow_data, by = "donor") |>
    dplyr::mutate(
      donor = stringr::str_wrap(donor, width = 40),
      recipient = stringr::str_wrap(recipient, width = 40)
    )
  
  # ---- STEP 6: Plot ----
  p <- ggplot2::ggplot(
    df_plot,
    ggplot2::aes(y = recipient, x = donor, fill = total_usd)
  ) +
    
    ggplot2::geom_tile(color = "white", linewidth = 0.3) +
    
    ggplot2::geom_text(
      ggplot2::aes(
        label = scales::label_number(
          scale_cut = scales::cut_short_scale(),
          accuracy = 0.1
        )(total_usd),
        color = total_usd
      ),
      size = 3.5, fontface = "bold"
    ) +
    
    ggplot2::scale_fill_viridis_c(
      option = "plasma",
      na.value = "grey85",
      labels = scales::label_number(accuracy = 0.1),
      name = "Funding (USD)"
    ) +
    
    ggplot2::scale_color_gradient(
      guide = "none",
      high= "black",
      low  = "white"
    ) +
    
    unhcrthemes::theme_unhcr(
      grid = TRUE,
      axis = FALSE,
      legend = FALSE,
      axis_title = FALSE
    ) +
    
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
    ) +
    
    ggplot2::labs(
      title = paste0("Top ", top_n, " Donors to Recipients for ", destination_name),
      subtitle = "Organization-level flows extracted from FTS nested structures",
      x = "Recipient Organization",
      y = "Donor Organization",
      caption = "Source: UN OCHA FTS API"
    )
  
  return(p)
}
