# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Donor Cluster Coverage
#'
#' Visualizes which humanitarian clusters each donor supports, using the number of
#' flows per cluster. Useful to understand donor focus and alignment with 
#' sector priorities.
#'
#' @param flows FTS flows dataframe.
#' @param donor_name Donor organization name.
#'
#' @return A ggplot object showing donor funding coverage across clusters.
#' @importFrom ggplot2 ggplot aes geom_col labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @importFrom stats reorder
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_donor_cluster_coverage(flows, donor_name= "Spain, Government of")
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_donor_cluster_coverage <- function(flows, donor_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization", 
                  sourceObjects_name == donor_name) |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type %in% c( "GlobalCluster")) |>
    dplyr::rename(name = destinationObjects_name ) |>
    dplyr::group_by(name) |>
    dplyr::summarise(flows_per_cluster = dplyr::n()) |>
    dplyr::ungroup()
  
  ggplot2::ggplot(df, ggplot2::aes(x = reorder(factor(name), flows_per_cluster),
                                   y = flows_per_cluster)) +
    ggplot2::geom_col() +
    ggplot2::coord_flip()+
    ggplot2::labs(
      title = paste0("Cluster Coverage by Donor: ", donor_name),
      subtitle = "Number of flows per humanitarian cluster",
      x = "Cluster",
      y = "Number of Flows",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "X", axis_title = FALSE) 
}
