# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Recipient Co-Funding Rate
#'
#' Shows how often a recipient shares funding with other recipients for 
#' a given donor.
#' Useful to see multi-recipient funding trends.
#'
#' @param flows A dataframe of FTS funding flows.
#' @param recipient_name Recipient organization name to filter.
#'
#' @return A ggplot object with co-funding rates.
#' @importFrom ggplot2 ggplot aes geom_col coord_flip labs  scale_y_continuous
#' @importFrom dplyr filter group_by summarise n_distinct mutate
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_recipient_cofunding(flows, 
#'               recipient_name = "United Nations High Commissioner for Refugees")
#'
#'
#' # getting LLm story
#' story <- generate_plot_story(p, max_tokens = 300)
#' cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p)
#' p + ggplot2::labs(subtitle = dubbed)
plot_recipient_cofunding <- function(flows, recipient_name) {
  
  df <- flows |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization", 
                  destinationObjects_name == recipient_name) |>
    dplyr::group_by(id) |>
    dplyr::summarise(recipient_count = dplyr::n_distinct(destinationObjects_name),
                     .groups = "drop") |>
    dplyr::mutate(shared = recipient_count > 1)
  
  cofunding_rate <- mean(df$shared, na.rm = TRUE)
  
  ggplot2::ggplot(data.frame(shared = c(cofunding_rate, 1 - cofunding_rate),
                             category = c("Shared", "Sole")), 
                  ggplot2::aes(x = category, y = shared)) +
    ggplot2::geom_col() +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste0("Co-Funding Rate for Recipient: ", recipient_name),
      subtitle = "Proportion of multi-recipient funding",
      x = "",
      y = "Proportion",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "X", axis_title = FALSE) 
}
