# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Donor Funding by Earmarking Type
#'
#' Visualizes the proportion of funding per earmarking type 
#' (Unearmarked, Softly earmarked, etc.)
#' for a selected donor. Helps understand donor flexibility and restrictions.
#'
#' @param flows A dataframe of humanitarian funding flows (FTS format).
#' @param donor_name Donor organization name to filter.
#'
#' @return A ggplot object showing donor funding by earmarking type.
#' @importFrom ggplot2 ggplot aes geom_col labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_donor_earmarking(flows, donor_name= "Spain, Government of")
#'
#' # getting LLm story
#' story <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini", max_tokens = 300)
#' # cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_donor_earmarking <- function(flows, donor_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization", 
                  sourceObjects_name == donor_name) |>
    tidyr::unnest(grandBargainEarmarkingType, names_repair = "unique") |>
    dplyr::group_by(grandBargainEarmarkingType) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = grandBargainEarmarkingType, 
                                   y = total_usd)) +
    ggplot2::geom_col(fill = "dodgerblue") +
    ggplot2::labs(
      title = paste0("Funding by Earmarking Type for Donor: ", donor_name),
      subtitle = "Distribution of funding across earmarking types",
      x = "Earmarking Type",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
