# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Donor Flow Type Distribution
#'
#' Shows the distribution of flow types 
#' (Standard, Parked, Pass-through, Carryover)
#' for a selected donor. Useful for understanding donor engagement complexity.
#'
#' @param flows FTS flows dataframe.
#' @param donor_name Donor organization name.
#'
#' @return A ggplot object showing flow type proportions.
#' @importFrom ggplot2 ggplot aes geom_col labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_donor_flowtype(flows, donor_name= "Spain, Government of")
#'
#' # getting LLm story
#' story <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini", max_tokens = 300)
#' # cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_donor_flowtype <- function(flows, donor_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization",
                  sourceObjects_name == donor_name) |>
    dplyr::group_by(flowType) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = flowType, y = total_usd)) +
    ggplot2::geom_col(fill = "purple") +
    ggplot2::labs(
      title = paste0("Flow Type Distribution for Donor: ", donor_name),
      subtitle = "Funding by flow type",
      x = "Flow Type",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
