# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Funding Timeline by Status
#'
#' Shows the evolution of funding amounts by status (pledge, commitment, paid)
#' across budget years. Useful for tracking donor disbursement progress.
#'
#' @param flows FTS flows dataframe.
#'
#' @return A ggplot object showing funding over time by status.
#' @importFrom ggplot2 ggplot aes geom_line geom_point labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_funding_status_timeline(flows)
#'
#' # getting LLm story
#' story <- generate_plot_story(p, max_tokens = 300)
#' cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p)
#' p + ggplot2::labs(subtitle = dubbed)
plot_funding_status_timeline <- function(flows) {
  
  df <- flows |>
    dplyr::group_by(budgetYear, status) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE), .groups = "drop")
  
  ggplot2::ggplot(df, ggplot2::aes(x = as.integer(budgetYear), 
                                   y = total_usd, 
                                   color = status)) +
    ggplot2::geom_line(size = 1) +
    ggplot2::geom_point(size = 2) +
    ggplot2::labs(
      title = "Funding Timeline by Status",
      subtitle = "Evolution of pledge, commitment, and paid funding",
      x = "Budget Year",
      y = "Funding (USD)",
      color = "Status",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
