# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Donor Funding Over Time
#'
#' Visualizes the total funding provided by a given donor across budget years.
#' Useful to track trends, identify peaks, and assess consistency.
#'
#' @param flows A dataframe of humanitarian funding flows (FTS format).
#' @param donor_name The name of the donor organization to filter.
#'
#' @return A ggplot object showing donor funding trends over budget years.
#' @importFrom ggplot2 ggplot aes geom_col geom_line geom_point labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_donor_funding_over_time(flows, donor_name= "Spain, Government of")
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' print(p + ggplot2::labs(subtitle = dubbed))
#'
plot_donor_funding_over_time <- function(flows, donor_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization",
                  sourceObjects_name == donor_name) |>
    dplyr::group_by(budgetYear) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = as.integer(budgetYear), y = total_usd)) +
    ggplot2::geom_col(fill = "steelblue") +
    ggplot2::geom_line(group = 1, color = "darkred", size = 1) +
    ggplot2::geom_point(color = "darkred", size = 2) +
    ggplot2::labs(
      title = paste0("Funding Trends for Donor: ", donor_name),
      subtitle = "Total funding per budget year",
      x = "Budget Year",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}

