# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Recipient Funding by Contribution Type
#'
#' Visualizes the split of funding received by a recipient based on 
#' contribution type
#' (e.g., financial or in-kind). Useful to assess funding modality diversity.
#'
#' @param flows FTS flows dataframe.
#' @param recipient_name Recipient organization name.
#'
#' @return A ggplot object showing funding by contribution type.
#' @importFrom ggplot2 ggplot aes geom_col labs  scale_y_continuous
#' @importFrom dplyr filter group_by summarise n_distinct mutate
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_recipient_contribution_type(flows, 
#'                 recipient_name = "United Nations High Commissioner for Refugees")
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_recipient_contribution_type <- function(flows, recipient_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(destinationObjects, 
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization",
                  destinationObjects_name == recipient_name) |>
    dplyr::group_by(contributionType) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = contributionType, y = total_usd)) +
    ggplot2::geom_col() +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste0("Funding by Contribution Type for Recipient: ",
                     recipient_name),
      subtitle = "Distribution of financial vs in-kind contributions",
      x = "Contribution Type",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
