# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Grand Bargain Earmarking by Recipient
#'
#' Visualizes the proportion of funding earmarked under the Grand Bargain 
#' commitments for each recipient. Helps to assess how much funding aligns 
#' with international humanitarian reform commitments.
#'
#' @param flows FTS flows dataframe.
#' @param recipient_name Recipient organization name.
#'
#' @return A ggplot object showing the split of earmarked vs non-earmarked 
#' funding.
#' @importFrom ggplot2 ggplot aes geom_col labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_recipient_grandbargain(flows,
#'           recipient_name = "United Nations High Commissioner for Refugees")
#'
#' # getting LLm story
#' story <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini", max_tokens = 300)
#' # cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p, provider = "azure", model = "gpt-4.1-mini")
#' p + ggplot2::labs(subtitle = dubbed)
plot_recipient_grandbargain <- function(flows, recipient_name) {
   flows <- filter_flows_for_indicators(flows)
  df <- flows |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization", 
                  destinationObjects_name == recipient_name) |>
    tidyr::unnest(grandBargainEarmarkingType, names_repair = "unique") |>
    dplyr::group_by(grandBargainEarmarkingType) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE)) |>
    dplyr::mutate(grandBargainEarmarkingType = factor(grandBargainEarmarkingType,
        levels= c("unearmarked", "softly earmarked", 
                  "earmarked", "tightly earmarked")))
  
  ggplot2::ggplot(df, ggplot2::aes(x = grandBargainEarmarkingType, 
                                   y = total_usd)) +
    ggplot2::geom_col() +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(
      labels = scales::label_number(scale_cut = scales::cut_short_scale())
    ) +
    ggplot2::labs(
      title = paste0("Recipient Grand Bargain Earmarking for ", recipient_name),
      subtitle = "Distribution of earmarked vs non-earmarked funding",
      x = "Earmarking Type",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
