# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Destination Funding by Donor
#'
#' Shows funding received at a location from multiple donors.
#' Useful to identify funding hotspots or dependency.
#'
#' @param flows FTS flows dataframe.
#' @param location_name Destination location name.
#'
#' @return A ggplot object showing total funding per donor for the location.
#' @importFrom ggplot2 ggplot aes geom_col coord_flip labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_location_funding_donor(flows, location_name= "Burundi")
#'
#' # getting LLm story
#' story <- generate_plot_story(p, max_tokens = 300)
#' cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p)
#' p + ggplot2::labs(subtitle = dubbed)
plot_location_funding_donor <- function(flows, location_name) {
  df <- flows |>
    tidyr::unnest(destinationObjects,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Location",
                  destinationObjects_name == location_name) |>
    tidyr::unnest(sourceObjects,
                  names_repair = "unique",
                  names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::group_by(sourceObjects_name) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = reorder(sourceObjects_name, total_usd),
                                   y = total_usd)) +
    ggplot2::geom_col(fill = "darkorange") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste0("Funding for Destination: ", location_name),
      subtitle = "Funding contributed by each donor",
      x = "Donor",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "X",
                             axis = "Y",
                             axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
