# WARNING - Generated by {fusen} from dev/flat_dev_5_visualisation2.Rmd: do not edit by hand # nolint: line_length_linter.

#' Plot Recipient Funding Composition by Donor
#'
#' Shows how a specific recipient organization’s funding is distributed across 
#' donors.
#' Useful for assessing donor diversification and reliance.
#'
#' @param flows A dataframe of humanitarian funding flows (FTS format).
#' @param recipient_name The name of the recipient organization to filter.
#'
#' @return A ggplot object showing donor shares of recipient funding.
#' @importFrom ggplot2 ggplot aes geom_col coord_flip labs  scale_y_continuous
#' @importFrom dplyr  filter group_by summarise
#' @importFrom tidyr unnest
#' @import unhcrthemes
#' @export
#' @examples
#' p <- plot_recipient_funding_composition(flows, 
#'               recipient_name = "United Nations High Commissioner for Refugees")
#'
#' # getting LLm story
#' story <- generate_plot_story(p, max_tokens = 300)
#' cat(story)
#' # and plot with more powerful subtitle
#' dubbed <- generate_plot_story(p)
#' p + ggplot2::labs(subtitle = dubbed)
plot_recipient_funding_composition <- function(flows, recipient_name) {
  
  df <- flows |>
    tidyr::unnest(destinationObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(destinationObjects_type == "Organization", 
                  destinationObjects_name == recipient_name) |>
    tidyr::unnest(sourceObjects, names_repair = "unique", names_sep = "_") |>
    dplyr::filter(sourceObjects_type == "Organization") |>
    dplyr::group_by(sourceObjects_name) |>
    dplyr::summarise(total_usd = sum(amountUSD, na.rm = TRUE))
  
  ggplot2::ggplot(df, ggplot2::aes(x = reorder(sourceObjects_name, total_usd),
                                   y = total_usd)) +
    ggplot2::geom_col(fill = "forestgreen") +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title = paste0("Funding Composition for Recipient: ", recipient_name),
      subtitle = "Funding received by donor organization",
      x = "Donor",
      y = "Funding (USD)",
      caption = "Source: OCHA Finantial Tracking Service (Flow API)"
    ) +
    unhcrthemes::theme_unhcr(grid = "X", axis = "X", axis_title = FALSE) +
    ggplot2::scale_y_continuous(labels = scales::comma)
}
